// Adversarial probes. PASS means the desired invariant holds; FAIL is retained evidence.
// Model output is deliberately controlled to isolate backend failures. No API or DB.
const fs=require('node:fs'),path=require('node:path');
const {decide}=require('../../inbox/ai/v2'),state=require('../../inbox/ai/v2/state'),composer=require('../../inbox/ai/v2/compose'),contracts=require('../../inbox/ai/v2/contracts'),context=require('../../inbox/ai/v2/context');
const defaults=require('../../inbox/ai/defaults'),kb=require('../../inbox/ai/structuredKnowledge');
const records=[...defaults.records,...kb.seeds],config={...defaults.config,model:'offline-fixture',maxResponseLength:4000,invoicesEnabled:true};
const signal=()=>({value:false,evidence:{messageId:'',text:''}});
const interpretation=(text,fields={},extra={})=>({intents:['advertising'],questions:[],facts:Object.entries(fields).map(([field,value])=>({field,value:String(value),itemId:'',explicit:true,confidence:1,correction:true,evidence:{messageId:'input',text}})),answeredQuestionIds:[],recommendations:[],unresolvedReferences:[],negotiation:signal(),deferral:signal(),humanRequest:signal(),paymentClaim:signal(),sensitiveCase:signal(),topic:'advertising',purchaseChange:{action:'none',path:'unchanged',evidence:{messageId:'',text:''}},confidence:1,...extra});
const seed=fields=>state.projection(state.merge({},interpretation('seed',fields),context.build({text:'seed'}),records).state);
const base={services:'ads_management',platforms:'tiktok',budget:'5000',budgetBasis:'daily',duration:'7'};
const results=[];
async function probe(id,description,run,check){try{const actual=await run();results.push({id,description,pass:!!check(actual),actual});}catch(e){results.push({id,description,pass:false,error:e.message});}}
async function turn(text,fields={},old={},extra={},options={}){const phases=[];const r=await decide({text,state:old,history:[],records,config,type:'text',...options},{call:async(phase,input)=>{phases.push(phase);return {model:'controlled-perfect-interpretation',value:phase==='interpretation'?interpretation(text,fields,extra):phase==='selection'?{entries:[],unsupportedQuestions:[]}:{parts:[{kind:'text',value:'The campaign is monitored by our team.'}],usedKnowledge:[]}};}});return {action:r.action,response:r.response,question:r.question,amount:r.amount,state:r.state,handoff:r.handoff,phases,debug:r.debug};}
const request=text=>[{text,evidence:{messageId:'input',text}}];
(async()=>{
 await probe('D01','Mixed per-platform service selection must not become Cartesian products',()=>turn('Set up TikTok but manage Meta',{services:'account_setup,ads_management',platforms:'tiktok,meta'}),r=>r.state.core.items.length===2&&r.state.core.items.some(i=>i.id==='tiktok:account_setup')&&r.state.core.items.some(i=>i.id==='meta:ads_management'));
 await probe('D02','Deferral after proceed=yes must pause payment pressure',()=>turn('Let me think',{},seed({...base,proceed:'yes'}),{deferral:{value:true,evidence:{messageId:'input',text:'Let me think'}}}),r=>r.state.core.readiness==='deferred'&&!r.question);
 await probe('D03','Explicit no after prior yes must stop payment pressure',()=>turn('No, not now',{proceed:'no'},seed({...base,proceed:'yes'})),r=>!r.question);
 await probe('D04','Negotiation cannot suppress useful questions in the same turn',()=>turn('Reduce it and explain management',{},seed(base),{questions:request('Reduce it and explain management'),negotiation:{value:true,evidence:{messageId:'input',text:'Reduce it and explain management'}}}),r=>r.phases.includes('composition'));
 await probe('D05','Non-question knowledge triggers must run semantic retrieval',()=>turn('I need reassurance before buying',{},seed(base)),r=>r.phases.includes('selection'));
 await probe('D06','Benign password question must remain visible for interpretation',()=>context.build({text:'Will I need to share my password?'}),r=>r.messages[0].text==='Will I need to share my password?');
 await probe('D07','Complete customer messages longer than 6000 chars must not silently truncate',()=>{const text='a'.repeat(6001)+' Actually Meta';const c=context.build({text});return {raw:text.length,seen:c.messages[0].text.length,tail:c.messages[0].text.slice(-20)};},r=>r.raw===r.seen);
 await probe('D08','Natural-language false guarantee must be rejected by deterministic output validation',()=>{const plan={action:'reply',facts:{},requiredFacts:[],question:null};let blocked=false;try{composer.render({parts:[{kind:'text',value:'We guarantee that every campaign will bring sales.'}],usedKnowledge:[]},plan,[],config);}catch{blocked=true;}return {blocked};},r=>r.blocked);
 await probe('D09','Spelled payment confirmation must be rejected',()=>{let blocked=false;try{composer.render({parts:[{kind:'text',value:'Your payment has been received successfully.'}],usedKnowledge:[]},{action:'reply',facts:{},requiredFacts:[],question:null},[],config);}catch{blocked=true;}return {blocked};},r=>r.blocked);
 await probe('D10','No invoice on explicit refusal with prior payment consent',()=>turn('No, not yet',{paymentRequested:'no'},seed({...base,proceed:'yes',paymentRequested:'yes'})),r=>r.action!=='invoice'&&!r.question);
 await probe('D11','Only one item changes duration; other selected plans remain intact',()=>{const old=seed({services:'ads_management',platforms:'tiktok,meta'});for(const id of ['tiktok:ads_management','meta:ads_management'])old.core.facts[`${id}:plan`]={value:'plan_7',status:'CONFIRMED'};const i=interpretation('Ten days');i.facts=[{field:'duration',value:'10',itemId:'tiktok:ads_management',explicit:true,confidence:1,correction:true,evidence:{messageId:'input',text:'Ten days'}}];return state.merge(old,i,context.build({text:'Ten days'}),records).state;},r=>!!r.facts['meta:ads_management:plan']);
 await probe('D12','Multi-question course detour should not early-return before handling other questions',()=>turn('Explain the course and management',{},seed(base),{topic:'course',questions:request('Explain the course and management')}),r=>r.phases.includes('composition'));
 await probe('D13','Financial values in generated prose are blocked',()=>{let blocked=false;try{composer.render({parts:[{kind:'text',value:'It costs ₦1.'}],usedKnowledge:[]},{action:'reply',facts:{},requiredFacts:[],question:null},[],config);}catch{blocked=true;}return {blocked};},r=>r.blocked);
 await probe('D14','False evidence cannot change platform',()=>{const i=interpretation('Meta',{platforms:'meta'});i.facts[0].evidence.text='absent';return state.merge(seed(base),i,context.build({text:'Hello'}),records);},r=>state.valueOf(r.state,'platforms')[0]==='tiktok'&&r.rejected.length===1);
 await probe('D15','Actual sent question wins over later unsent draft',()=>context.build({text:'second',history:[{_id:'sent',direction:'outbound',status:'sent',text:'Actual question',automation:{question:{purpose:'SERVICE'}},sentAt:'2026-01-01'},{_id:'draft',direction:'outbound',status:'queued',text:'Not seen',automation:{question:{purpose:'PLATFORM'}},createdAt:'2026-01-02'}]}),r=>r.pendingQuestion.id==='sent');
 await probe('D16','Payment claimed is never automatically paid',()=>turn('I paid',{},seed(base),{paymentClaim:{value:true,evidence:{messageId:'input',text:'I paid'}}}),r=>r.action==='handoff'&&r.state.paymentStatus!=='paid');
 await probe('D17','Daily custom pricing uses calculator',()=>turn('Five thousand daily for two days',{...base,duration:'2'}),r=>r.amount===35000);
 await probe('D18','Seven-day package includes management exactly once',()=>turn('One week',{services:'ads_management',platforms:'tiktok',duration:'7'}),r=>r.amount===60000);
 await probe('D19','Selected 15-day advertised package can be quoted without forced handoff',()=>turn('Fifteen days',{services:'ads_management',platforms:'tiktok',duration:'15'}),r=>r.action==='reply'&&r.amount===285000);
 await probe('D20','Knowledge selected for mandatory handoff on statement is actually enforced',()=>turn('Custom business stop condition',{},seed(base),{}, {records:[...records,{kind:'knowledge',key:'mandatory',enabled:true,data:{forceHandoff:true,handoffReason:'MANDATORY',semanticTrigger:'Custom business stop condition'}}]}),r=>r.action==='handoff');
 await probe('D21','All-inclusive budget can be represented distinctly in interpretation contract',()=>({basis:contracts.fields.budgetBasis}),r=>r.basis.some(x=>/inclusive|package/.test(x)));
 await probe('D22','Legacy continuation does not discard facts outside six-message history',()=>turn('Proceed please',{}, {selectedPlatform:'tiktok',serviceType:'account_setup',quotedAmount:20000}),r=>r.question?.purpose!=='SERVICE');
 await probe('D23','Administrative template cannot insert a stale price bypassing validator',()=>turn('Hello',{}, {},{intents:['greeting']},{records:[...records.filter(r=>r.key!=='generic_first_contact'),{kind:'knowledge',key:'generic_first_contact',data:{preferredResponse:'Everything costs ₦1. Transfer to 1234567890.'}}]}),r=>!r.response?.includes('₦1'));
 await probe('D24','Unauthenticated model text cannot invent a bare payment destination',()=>{let blocked=false;try{composer.render({parts:[{kind:'text',value:'Pay at evil.example/pay now.'}],usedKnowledge:[]},{action:'reply',facts:{},requiredFacts:[],question:null},[],config);}catch{blocked=true;}return {blocked};},r=>r.blocked);
 await probe('D25','New correction retains unrelated confirmed duration',()=>turn('Actually Meta',{platforms:'meta'},seed(base)),r=>state.valueOf(r.state.core,'duration')===7&&state.valueOf(r.state.core,'budget')===5000);
 await probe('D26','Unquotable corrected selection must clear compatibility quotedAmount',async()=>{const old=seed(base);old.quotedAmount=60000;return turn('Add Meta too',{platforms:'tiktok,meta'},old);},r=>!r.state.quotedAmount);
 await probe('D27','Deferral with old proceed and paymentRequested must never create invoice intent',()=>turn('Wait, let me decide tomorrow',{},seed({...base,proceed:'yes',paymentRequested:'yes'}),{deferral:{value:true,evidence:{messageId:'input',text:'Wait, let me decide tomorrow'}}}),r=>r.action!=='invoice');
 await probe('D28','One STRICT source must not forbid natural explanation from a second KNOWLEDGE source',()=>contracts.forInput('composition',{knowledge:[{key:'strict',quoteable:true,mode:'STRICT',allowContext:false},{key:'facts',quoteable:false,mode:'KNOWLEDGE',allowContext:true}],plan:{facts:{},question:null}}),r=>r.properties.parts.items.anyOf.some(v=>v.properties.kind.enum.includes('text')));
 await probe('D29','Renewed explicit proceed should recover from an earlier deferral',async()=>{const a=await turn('Later',{},seed(base),{deferral:{value:true,evidence:{messageId:'input',text:'Later'}}});return turn('Now I want to proceed',{proceed:'yes'},a.state);},r=>r.state.core.readiness==='ready'&&r.question?.purpose==='PAYMENT');
 await probe('D30','Ordinary factual statements must not re-ask the same unanswered sales question indefinitely',async()=>{let old=seed({...base,proceed:'yes'}),history=[],questions=[];for(let i=0;i<12;i++){const r=await turn('I am still discussing it with my partner',{},old,{deferral:{value:true,evidence:{messageId:'input',text:'I am still discussing it with my partner'}}},{history});old=r.state;questions.push(r.question?.purpose||null);history.push({_id:`answer-${i}`,direction:'outbound',status:'sent',text:r.response,automation:{question:r.question},sentAt:new Date().toISOString()});}return {questions,repeats:questions.filter(Boolean).length};},r=>r.repeats===0);
 await probe('D31','Existing invoice must retain PAYMENT_PENDING stage after a factual answer',()=>turn('What happens next?',{}, {...seed(base),invoiceId:'synthetic',invoiceAmount:60000,currentSalesStage:'PAYMENT_PENDING'},{questions:request('What happens next?')},{invoiceRecord:{status:'pending',amount:60000}}),r=>r.state.currentSalesStage==='PAYMENT_PENDING');
 await probe('D32','Confirmed invoice amount beats changed catalogue price',()=>turn('Details please',{}, {...seed(base),invoiceId:'synthetic',invoiceAmount:55000},{questions:request('Details please')},{invoiceRecord:{status:'pending',amount:55000}}),r=>r.amount===55000);
 await probe('D33','Course exploration preserves existing advertising facts',()=>turn('Tell me about the course',{},seed(base),{topic:'course',questions:request('Tell me about the course')}),r=>r.state.core.purchasePath==='advertising'&&state.valueOf(r.state.core,'budget')===5000);
 await probe('D34','Media produces actual handoff intent before interpretation',()=>turn('[audio]',{},seed(base),{},{type:'audio'}),r=>r.action==='handoff'&&r.handoff==='MEDIA_RECEIVED'&&r.phases.length===0);
 const report={kind:'controlled semantic interpretation and direct invariants; not language-model accuracy',total:results.length,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,results};fs.writeFileSync(path.join(__dirname,'offline-results.json'),JSON.stringify(report,null,2));for(const r of results)console.log(`${r.pass?'PASS':'FAIL'} ${r.id} ${r.description}`);console.log(JSON.stringify({total:report.total,passed:report.passed,failed:report.failed}));
})();
