const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const scored=JSON.parse(fs.readFileSync(path.join(__dirname,'adjudicated-results.json')));
const groups={};let calls=0,input=0,output=0,unchanged=true;
for(const r of scored){const raw=JSON.parse(fs.readFileSync(path.join(__dirname,r.file)));calls+=raw.calls;for(const s of raw.scenarios)for(const t of s.rows){input+=t.result?.usage?.input_tokens||0;output+=t.result?.usage?.output_tokens||0;}for(const [f,h]of Object.entries(raw.hashes)){if(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../../inbox/ai/v2',f))).digest('hex')!==h)unchanged=false;}
 const g=groups[r.model]||=(new Map());for(const s of r.scenarios){const prev=g.get(s.id);if(!prev||prev.status==='INCONCLUSIVE_PROVIDER'||(s.status!=='INCONCLUSIVE_PROVIDER'&&raw.started>prev.started))g.set(s.id,{...s,file:r.file,started:raw.started});}}
const text=['V2 ADVERSARIAL EVALUATION — FINAL SUMMARY','6 October 2026','','Release decision: NO-GO. No deployment, production data change, or engine fix.','',`V2 JavaScript hashes unchanged across evaluation: ${unchanged}`,`API call attempts across recorded runs: ${calls}`,`Recorded completed-response token usage: input=${input}, output=${output}. This is not a billing statement.`, '','The initial batch contains provider failures. Raw pass/fail flags were NOT used as final accuracy scores.','Adjudication separates provider failures and handles effective per-item facts and equivalent knowledge sources.',''];
for(const [name,map]of Object.entries(groups)){const rows=[...map.values()];const counts=Object.fromEntries(['PASS','FAIL','INCONCLUSIVE_PROVIDER'].map(s=>[s,rows.filter(r=>r.status===s).length]));text.push(`${name}: latest evaluable outcome per scenario: ${JSON.stringify(counts)}`);for(const r of rows.filter(x=>x.status==='FAIL'))text.push(`  FAIL ${r.id}: ${r.errors.join('; ')}`);text.push('');}
text.push('Provider blocker: final serial run returned HTTP 429 / credit_balance_exhausted / insufficient_quota.','No more API calls were made after reading this explicit blocker. Do not assume the first run had the same subtype.','The main serial run stopped with eight scenarios not started; its human-request result was provider-blocked.','The 15-turn real-model journey was not completed. A controlled 12-turn replay reproduced twelve repeated PAYMENT questions.','', 'Offline: 34 adversarial probes, 11 passed, 23 failed. This selected challenge set is not a production failure-rate estimate.','Ephemeral DB: 3 existing isolation/Test Agent/rollback integration tests passed.','', 'Representative verified failures:', '- Perfect interpretation of a fresh deferral can still produce invoice intent when historical consent exists (D27).','- Mixed platform/service requests lose associations or produce unintended purchases (D01, real mixed-platform-services).','- “100k for the whole thing” produced 130000 in the GPT-4.1 synthetic test.','- GPT-4.1-mini added setup to a manage-only daily-budget request, yielding 80000 instead of 60000.','- Ordinary management/expected-reach questions sometimes hand off on duplicate response components.','- Output validation accepts some false payment confirmations, guarantees and bare payment domains (controlled injection, not real customer delivery).','', 'What succeeded:', '- Multiple contextual service choices and single-platform multi-fact extraction.','- Same-turn requirements retrieval after platform/service update.','- Daily 5000 for 2 days => 35000; seven-day plan => 60000 including management (offline).','- Invalid evidence rejected; actual sent question excludes queued draft; payment claim does not mark paid.','- Corrected platform retains unrelated facts; genuine renewed consent can resume after deferral.','', 'Remaining limits:', '- No production log replay or live enabled-catalogue snapshot; local seeds + five synthetic KB fixtures.','- Harness response limit 4000 versus local default 1500; production-limit tests remain.','- No statistical multi-run reliability estimate, calibrated human quality panel or full concurrent financial fault injection.','- HTTP/provider failures are inconclusive for semantic quality, although current handoff-on-provider-failure behavior is a reliability concern.','', 'Read AUDIT.txt for the runtime-order audit, response-authority map, findings, file references and remediation/release gates.');
fs.writeFileSync(path.join(__dirname,'EVALUATION-SUMMARY.txt'),text.join('\n'));
console.log(text.slice(0,11).join('\n'));for(const [name,map]of Object.entries(groups))console.log(name,Object.fromEntries(['PASS','FAIL','INCONCLUSIVE_PROVIDER'].map(s=>[s,[...map.values()].filter(r=>r.status===s).length])));
