// Offline report generation only. No model calls, application changes or judge.
const fs=require('fs'),path=require('path'),base=__dirname;
const r=JSON.parse(fs.readFileSync(path.join(base,'raw-results.json')));
const notes=JSON.parse(fs.readFileSync(path.join(base,'review-notes.json')));
if(!r.finishedAt)throw Error('Evaluation still running');
const turns=r.scenarios.flatMap(s=>s.turns.map(t=>({...t,scenario:s.id}))),completed=turns.filter(t=>t.completed),calls=r.calls;
const totals={conversations:r.scenarios.length,plannedTurns:r.scenarios.reduce((n,s)=>n+s.turns.length+s.unreached.length,0),turnsAttempted:turns.length,turnsCompleted:completed.length,unreachedTurns:r.scenarios.reduce((n,s)=>n+s.unreached.length,0),interpreterCalls:0,composerCalls:0,composerRepairs:0,totalCalls:calls.length,inputTokens:0,cachedInputTokens:0,outputTokens:0,totalTokens:0,estimatedUSD:0,callsWithoutUsage:0,byModel:{}};
for(const c of calls){const stage=c.request.text.format.name.endsWith('interpreter')?'interpreter':'composer';totals[stage+'Calls']++;if(stage==='composer'&&c.request.input.some(i=>i.role==='developer'))totals.composerRepairs++;const m=totals.byModel[c.request.model]||={calls:0,inputTokens:0,cachedInputTokens:0,outputTokens:0,totalTokens:0,estimatedUSD:0,reasoning:c.request.reasoning.effort};m.calls++;if(!c.response?.usage){totals.callsWithoutUsage++;continue;}const u=c.response.usage;for(const [k,v]of Object.entries({inputTokens:u.input_tokens||0,cachedInputTokens:u.input_tokens_details?.cached_tokens||0,outputTokens:u.output_tokens||0,totalTokens:u.total_tokens||0,estimatedUSD:c.cost||0})){totals[k]+=v;m[k]+=v;}}
const median=a=>{a=[...a].sort((a,b)=>a-b);return a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;};
totals.cacheWriteTokens=0;for(const c of calls){const n=c.response?.usage?.input_tokens_details?.cache_write_tokens||0;totals.cacheWriteTokens+=n;const m=totals.byModel[c.request.model];m.cacheWriteTokens=(m.cacheWriteTokens||0)+n;}totals.returnedModels=[...new Set(calls.map(c=>c.response?.model).filter(Boolean))];totals.runElapsedSeconds=(new Date(r.finishedAt)-new Date(r.startedAt))/1000;
for(const t of turns){t.calls=calls.filter(c=>c.scenario===t.scenario&&c.turn===t.turn);t.cost=t.calls.reduce((n,c)=>n+(c.cost||0),0);t.debug=t.result?.debug||t.error?.debug||{};t.flags=[];const p=t.debug.interpreter,a=t.debug.answerPack;
 if(t.error)t.flags.push(t.error.message);
 if(a){if(a.resolutionError)t.flags.push('RESOLVER_REVIEW: '+a.resolutionError);if(a.unresolvedRequests?.length)t.flags.push('UNRESOLVED_KNOWLEDGE: '+a.unresolvedRequests.map(x=>x.type).join(', '));if(a.quote?.total>t.debug.stateChanges?.purchaseCap&&t.debug.stateChanges.purchaseCap)t.flags.push('QUOTE_ABOVE_CAP');if(a.verifiedPayment)t.flags.push('UNEXPECTED_PAID_STATE');if(['DEFERRED','DECLINED'].includes(a.readiness)&&a.actions.invoice)t.flags.push('INVOICE_WHILE_DEFERRED');if(p?.current_requests.some(x=>x.type==='REQUEST_HUMAN')&&!a.actions.handoff)t.flags.push('HANDOFF_OMITTED');if(p?.current_requests.some(x=>x.type==='ASK_PAYMENT_DETAILS')&&a.readiness==='READY_TO_PAY'&&a.quote&&!a.missing.length&&!a.actions.invoice)t.flags.push('INVOICE_OMITTED');
 const items=a.purchase||[];if(['B','C','G'].includes(t.scenario)&&items.some(x=>x.service==='ACCOUNT_SETUP'))t.flags.push('UNREQUESTED_SETUP');if(['A','F'].includes(t.scenario)&&items.some(x=>x.service==='ADS_MANAGEMENT'))t.flags.push('WRONG_SERVICE');if(t.scenario==='D'&&items.some(x=>!['TIKTOK:ACCOUNT_SETUP','META:ADS_MANAGEMENT'].includes(x.platform+':'+x.service)))t.flags.push('WRONG_MIXED_PAIR');if(a.quote?.items?.some(x=>x.creativeMode!=='testing'))t.flags.push('CREATIVE_OPTION_REVIEW');if(t.scenario==='C'&&t.turn>=2&&a.quote&&a.quote.total!==265000)t.flags.push('PACKAGE_PRICE_MISMATCH');
 }
 for(const c of t.debug.composition||[])for(const err of c.errors||[])t.flags.push('VALIDATION: '+err);
 t.flags=[...new Set(t.flags)];t.engineeringObservation=notes[t.scenario+t.turn]||'No additional issue identified in the limited inspection. Not an independent semantic pass.';
}
totals.averageCostPerCompletedTurn=completed.length?totals.estimatedUSD/completed.length:null;totals.averageCostPerConversation=totals.estimatedUSD/r.scenarios.length;totals.averageAttemptLatencyMs=turns.reduce((n,t)=>n+t.latencyMs,0)/turns.length;totals.medianAttemptLatencyMs=median(turns.map(t=>t.latencyMs));totals.averageCompletedLatencyMs=completed.length?completed.reduce((n,t)=>n+t.latencyMs,0)/completed.length:null;totals.slowestTurn=turns.reduce((a,t)=>!a||t.latencyMs>a.latencyMs?{scenario:t.scenario,turn:t.turn,latencyMs:t.latencyMs}:a,null);totals.highestCostTurn=turns.reduce((a,t)=>!a||t.cost>a.cost?{scenario:t.scenario,turn:t.turn,cost:t.cost}:a,null);totals.costNote='Observed returned usage at the frozen adapter standard rates; unreported usage is unknown, not assumed free. Average/completed includes failed-attempt spend.';
fs.writeFileSync(path.join(base,'usage-cost.json'),JSON.stringify(totals,null,2));fs.writeFileSync(path.join(base,'turn-review.json'),JSON.stringify(turns,null,2));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=v=>'<pre>'+esc(JSON.stringify(v,null,2))+'</pre>',detail=(label,v)=>'<details><summary>'+esc(label)+'</summary>'+json(v)+'</details>';
let html=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V4 acceptance — human review</title><style>body{font:16px/1.55 system-ui;background:#eef2f8;color:#14233b;max-width:1100px;margin:32px auto;padding:0 20px}h1,h2,h3{line-height:1.2}article,header{background:white;border:1px solid #d9e1ed;border-radius:14px;padding:24px;margin:18px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;background:#f4f6fa;padding:12px}.bubble{white-space:pre-wrap;padding:16px;border-radius:12px;background:#edf5ff}.answer{background:#eaf5e8}.error{color:#a82e2e}summary{cursor:pointer;padding:8px 0}nav a{margin-right:20px}small{color:#4d6077}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><header><h1>V4 acceptance — human review</h1><p>Eight fresh scenarios, once each. Real OpenAI calls; simulated actions only. No judge, fixes, deployment or activation.</p><p>Interpreter: gpt-6.1-sol / medium · Composer: gpt-6-luna / medium</p><p>${totals.turnsCompleted}/${totals.turnsAttempted} attempted turns completed; ${totals.unreachedTurns} unreached. ${totals.totalCalls} API calls. Observed estimated cost: $${totals.estimatedUSD.toFixed(6)}.</p><p>Flags identify review needs, not a subjective quality score. Read actual responses and raw evidence.</p><nav>${r.scenarios.map(s=>`<a href="#${s.id}">${s.id}</a>`).join('')}</nav>${detail('Usage and latency',totals)}</header>`;
for(const s of r.scenarios){html+=`<h2 id="${s.id}">${s.id}. ${esc(s.name)}</h2><p>Expected: ${esc(s.expected)}</p>`;for(const t of turns.filter(t=>t.scenario===s.id)){const p=t.debug.interpreter,a=t.debug.answerPack;html+=`<article><h3>Turn ${t.turn}</h3><b>CUSTOMER</b><p class="bubble">${esc(t.customer)}</p><div class="grid"><section><b>INTERPRETER SUMMARY</b>${json(p?{requests:p.current_requests.map(x=>({type:x.type,platform:x.platform,service:x.service})),purchase_change:p.purchase_change,readiness:p.readiness,facts:p.facts}:t.error)}</section><section><b>BACKEND DECISION</b>${json({operations:t.debug.operations,evidenceValidation:a?'passed':t.error?.message||'not reached',missing:a?.missing,actions:a?.actions,quote:a?.quote})}</section></div><b>SOURCES</b>${json({knowledge:a?.knowledge,authoritativeFacts:a?.facts})}<b>ANSWER PACK SUMMARY</b>${json({purchase:a?.purchase,readiness:a?.readiness,allowedQuestions:a?.allowedQuestions,unresolved:a?.unresolvedRequests})}<b>FINAL AI RESPONSE</b><p class="bubble answer">${esc(t.result?.response||'No accepted customer response')}</p><b>VALIDATION / SAFETY</b><p class="${t.flags.length?'error':''}">${esc(t.flags.join('; ')||'No automatic flag; manual semantic review still required')}</p><b>COST / LATENCY</b><p>$${t.cost.toFixed(6)} · ${(t.latencyMs/1000).toFixed(2)} seconds · ${t.calls.length} calls</p>${detail('Raw interpreter',p)}${detail('Complete Answer Pack',a)}${detail('Composer attempts and validation',t.debug.composition)}${detail('Model requests, responses and usage (no credentials)',t.calls)}${detail('Result / error',t.result||t.error)}</article>`;}if(s.unreached.length)html+=`<p class="error">Unreached after scenario stop: ${esc(s.unreached.join(' → '))}</p>`;}
html=html.replace('<nav>', '<p><a href="REPORT.txt">Full findings</a> · <a href="usage-cost.json">Usage JSON</a> · <a href="raw-results.json">Raw results</a></p><details><summary>Engineering observations by turn</summary>'+Object.entries(notes).map(([k,v])=>'<p><b>'+esc(k)+'</b> '+esc(v)+'</p>').join('')+'</details><nav>');
fs.writeFileSync(path.join(base,'HUMAN-REVIEW.html'),html);console.log(JSON.stringify(totals,null,2));
