const {test}=require('node:test'),assert=require('node:assert/strict');
const states=require('./state'),{build}=require('./context'),{decide}=require('./index'),composer=require('./compose'),authority=require('./authority'),consent=require('./consent'),defaults=require('../defaults'),kb=require('../structuredKnowledge');
const records=[...defaults.records,...kb.seeds],config={...defaults.config,model:'fixture',invoicesEnabled:true,maxResponseLength:4000};
let count=0;
function interpretation(text,extra={}){const id=`customer-${++count}`,evidence={messageId:id,text};const signal={value:false,evidence:{messageId:'',text:''}};return {id,evidence,value:{items:[],decisions:[],budgets:[],requests:[],facts:[],questions:[],recommendations:[],answeredQuestionIds:[],unresolvedReferences:[],intents:['advertising'],topic:'advertising',purchaseChange:{action:'none',path:'unchanged',evidence:signal.evidence},negotiation:signal,deferral:signal,humanRequest:signal,paymentClaim:signal,sensitiveCase:signal,confidence:1,...extra}};}
const fact=(f,value,x,itemId='')=>({field:f,value:String(value),itemId,explicit:true,confidence:1,correction:true,evidence:x.evidence});
const item=(platform,serviceType,x,replaces='')=>({action:'add',platform,serviceType,replaces,explicit:true,confidence:1,evidence:x.evidence});
const event=(type,x,scope='purchase')=>({type,scope,explicit:true,confidence:1,evidence:x.evidence});
const budget=(kind,amount,x,itemId='')=>({kind,amount,itemId,explicit:true,confidence:1,evidence:x.evidence});
const need=(type,x,id='r1')=>({id,type,text:x.evidence.text,evidence:x.evidence,itemId:'',questionId:''});
function merge(old,x){return states.projection(states.merge(old,x.value,build({messages:[{_id:x.id,text:x.evidence.text}]}),records).state,old);}
function seed(){const x=interpretation('Set up TikTok');x.value.items=[item('tiktok','account_setup',x)];return merge({},x);}
async function run(old,x,options={}){
 const phases=[];const result=await decide({state:old,messages:[{_id:x.id,text:x.evidence.text}],text:x.evidence.text,type:'text',history:[],records,config,...options.args},{call:async(phase,input)=>{phases.push(phase);let value;
  if(phase==='interpretation')value=x.value;
  else if(phase==='selection')value=options.selection||{entries:[],unsupportedQuestions:[]};
  else if(phase==='composition')value=options.composition||{parts:[...(options.prose?[{kind:'text',value:options.prose}]:[]),...input.plan.requiredFacts.map(value=>({kind:'fact',value})),...(input.plan.question?[{kind:'question',value:input.plan.question.purpose}]:[])],usedKnowledge:[]};
  else value=options.grounding?options.grounding(input):require('./fixtures').grounding(input);
  return {value,model:'fixture'};
 }});return {...result,phases};
}
for(const type of ['DEFERRED','DECLINED'])test(`historical payment request cannot override ${type}`,async()=>{let s=seed();let x=interpretation('Send account');x.value.decisions=[event('PAYMENT_REQUESTED',x)];s=merge(s,x);x=interpretation('Wait until tomorrow');x.value.decisions=[event(type,x)];const r=await run(s,x);assert.equal(r.action,'reply');assert.equal(r.question,null);assert.equal(r.state.customerWantsToProceed,false);assert.equal(r.state.paymentDetailsRequested,false);assert(consent.effective(r.state.core).blocked);});
test('12 deferral/support turns do not repeat payment pressure; explicit resume works',async()=>{let s=seed(),x=interpretation('Send account');x.value.decisions=[event('PAYMENT_REQUESTED',x)];s=merge(s,x);for(let n=0;n<12;n++){x=interpretation(`Think first ${n}`);if(n===0)x.value.decisions=[event('DEFERRED',x)];x.value.requests=[need('ask_support_question',x)];const r=await run(s,x,{prose:'The campaign is monitored.'});assert.equal(r.action,'reply',r.error);assert.equal(r.question,null);assert.equal(r.state.paymentDetailsRequested,false);s=r.state;}x=interpretation('Ready now');x.value.decisions=[event('RESUMED',x)];const r=await run(s,x);assert.equal(r.question.purpose,'PAYMENT');});
test('later evidence inside one multi-message turn wins over earlier consent',()=>{const c=build({messages:[{_id:'a',text:'Send it'},{_id:'b',text:'Wait'}]});const x=interpretation('unused');x.value.decisions=[{...event('DEFERRED',x),evidence:{messageId:'b',text:'Wait'}},{...event('PAYMENT_REQUESTED',x),evidence:{messageId:'a',text:'Send it'}}];const s=states.merge(seed(),x.value,c,records).state;assert(consent.effective(s).blocked);});
test('changing a price input during deferral does not silently resume',()=>{let s=seed(),x=interpretation('Later');x.value.decisions=[event('DEFERRED',x)];s=merge(s,x);x=interpretation('Actually Meta');x.value.items=[item('meta','account_setup',x,'tiktok:account_setup')];s=merge(s,x);assert(consent.effective(s.core).blocked);});
for(const selections of [[['tiktok','account_setup'],['meta','ads_management']],[['tiktok','account_setup'],['tiktok','ads_management']],[['tiktok','ads_management'],['meta','ads_management']]])test(`explicit relationships ${JSON.stringify(selections)}`,async()=>{const x=interpretation('My selected services');x.value.items=selections.map(([p,t])=>item(p,t,x));const r=await run({},x);assert.deepEqual(r.state.core.items.map(i=>i.id),selections.map(([p,t])=>`${p}:${t}`));const next=interpretation('Okay');const r2=await run(r.state,next);assert.deepEqual(r2.state.core.items.map(i=>i.id),selections.map(([p,t])=>`${p}:${t}`));});
test('ambiguous old two-by-two slots never produce four charged items',async()=>{const x=interpretation('Both');x.value.facts=[fact('platforms','tiktok,meta',x),fact('services','account_setup,ads_management',x)];const r=await run({},x);assert.equal(r.question.purpose,'RELATIONSHIPS');assert.equal(r.amount,null);assert.equal(r.state.core.items.length,0);});
test('scoped duration invalidates only its item plan and quote',()=>{let x=interpretation('Manage both');x.value.items=[item('tiktok','ads_management',x),item('meta','ads_management',x)];let s=merge({},x);for(const i of s.core.items){i.quote={total:60000};s.core.facts[`${i.id}:plan`]={status:'CONFIRMED',value:'plan-seven'};}x=interpretation('Meta for ten days');x.value.facts=[fact('duration',10,x,'meta:ads_management')];s=merge(s,x);assert(s.core.facts['tiktok:ads_management:plan']);assert(s.core.items[0].quote);assert.equal(s.core.facts['meta:ads_management:plan'],undefined);assert.equal(s.core.items[1].quote,undefined);assert.equal(s.quotedAmount,undefined);});
for(const [kind,amount,expected]of [['DAILY_AD_SPEND',5000,60000],['TOTAL_AD_SPEND',100000,130000],['ALL_IN_CAP',100000,100000]])test(`budget meaning ${kind} uses calculator`,async()=>{const x=interpretation('Specified budget');x.value.items=[item('tiktok','ads_management',x)];x.value.budgets=[budget(kind,amount,x,'tiktok:ads_management')];x.value.facts=[fact('duration',7,x,'tiktok:ads_management')];const r=await run({},x);assert.equal(r.action,'reply',r.error);assert.equal(r.amount,expected);});
test('all-in cap includes selected setup fee exactly once',async()=>{const x=interpretation('Setup and manage for a week within total cap');x.value.items=[item('tiktok','account_setup',x),item('tiktok','ads_management',x)];x.value.budgets=[budget('ALL_IN_CAP',100000,x)];x.value.facts=[fact('duration',7,x,'tiktok:ads_management')];const r=await run({},x);assert.equal(r.amount,100000);assert.equal(r.state.core.quote.items.find(i=>i.itemId==='tiktok:account_setup').total,20000);});
test('impossible cap asks for clarification without invoice or discount',async()=>{const x=interpretation('My total cap');x.value.items=[item('tiktok','ads_management',x)];x.value.budgets=[budget('ALL_IN_CAP',15000,x)];x.value.facts=[fact('duration',7,x,'tiktok:ads_management')];x.value.decisions=[event('PAYMENT_REQUESTED',x)];const r=await run({},x);assert.equal(r.action,'reply');assert.equal(r.amount,null);assert.equal(r.question.purpose,'CAP');});
test('all platform cap is clarified rather than silently multiplied',async()=>{const x=interpretation('Both with a combined cap');x.value.items=[item('tiktok','ads_management',x),item('meta','ads_management',x)];x.value.budgets=[budget('ALL_IN_CAP',100000,x)];x.value.facts=[fact('duration',7,x)];const r=await run({},x);assert.equal(r.amount,null);assert.equal(r.question.purpose,'BUDGET_ALLOCATION');});
test('statement needs invoke knowledge selection after updated items',async()=>{const x=interpretation('TikTok setup, I need guidance');x.value.items=[item('tiktok','account_setup',x)];x.value.requests=[need('ask_requirements',x)];const r=await run({},x,{prose:'Use the approved onboarding process.'});assert(r.phases.includes('selection'));assert(r.phases.includes('composition'));assert.equal(r.state.selectedPlatform,'tiktok');assert.equal(r.debug.requestLedger[0].disposition,'ANSWERED');});
test('invoice request plus question must be composed before side effect intent returns',async()=>{const x=interpretation('Send account, does setup include ad spend?');x.value.decisions=[event('PAYMENT_REQUESTED',x)];x.value.requests=[need('request_invoice',x),need('ask_support_question',x,'r2')];const r=await run(seed(),x,{prose:'Advertising spend is separate.'});assert.equal(r.action,'invoice',r.error);assert.match(r.response,/Advertising spend is separate/);assert(r.phases.includes('composition'));assert.equal(r.debug.requestLedger.find(n=>n.id==='r2').disposition,'ANSWERED');});
test('missing request coverage fails closed after bounded repair',async()=>{const x=interpretation('Explain requirements');x.value.requests=[need('ask_requirements',x)];const r=await run(seed(),x,{prose:'Okay.',grounding:input=>({...require('./fixtures').grounding(input),coverage:[]})});assert.equal(r.action,'handoff');assert.equal(r.phases.filter(p=>p==='composition').length,2);assert.match(r.error,/Uncovered/);});
for(const [type,text]of [['PAYMENT_STATUS','Your payment has been received successfully.'],['GUARANTEE','Every campaign will bring sales.'],['DESTINATION','Pay at evil.example/pay.'],['PRICE','Your price is one naira.'],['DISCOUNT','We can reduce our fee.'],['PERMISSION','I can approve this action myself.']])test(`typed ${type} claim is rejected, including paraphrases`,async()=>{const p={action:'reply',facts:{},provenance:{},requiredFacts:[],question:null,ledger:[]},o={parts:[{kind:'text',value:text}],usedKnowledge:[]};await assert.rejects(()=>composer.validate(o,p,[],async()=>({segments:[{index:0,claims:[{text,type,sources:[],entailed:true}]}],coverage:[]})),/Unauthorized typed claim/);assert.throws(()=>composer.render(o,p,[],config),/provenance/);});
test('backend financial references cannot be forged or changed after issue',()=>{const p={action:'reply',facts:{},provenance:{},requiredFacts:[],question:null,ledger:[]};authority.fact(p,'quote','Approved amount','PRICE',{kind:'calculator'});p.facts.quote='Changed amount';assert.throws(()=>composer.render({parts:[{kind:'fact',value:'quote'}],usedKnowledge:[]},p,[],config),/Unissued/);});
test('strict warning and nonfinancial digit explanation coexist with provenance',async()=>{const k={key:'steps',data:{contentRole:'RESPONSE',responseMode:'STRICT',preferredResponse:'Use secure access.'}},k2={key:'guide',data:{contentRole:'KNOWLEDGE',facts:'There are 3 steps.'}};const p={action:'reply',facts:{},requiredFacts:[],question:null,ledger:[]},o={parts:[{kind:'knowledge',value:'steps'},{kind:'text',value:'There are 3 steps.'}],usedKnowledge:['steps','guide']};await composer.validate(o,p,[k,k2],async()=>({segments:[{index:0,claims:[{text:'Use secure access.',type:'BUSINESS_FACT',sources:['steps'],entailed:true}]},{index:1,claims:[{text:'There are 3 steps.',type:'BUSINESS_FACT',sources:['guide'],entailed:true}]}],coverage:[]}));assert.match(composer.render(o,p,[k,k2],config),/3 steps/);});
test('prepared quote does not set PRICE_PRESENTED; successful send does',async()=>{const x=interpretation('Set up TikTok');x.value.items=[item('tiktok','account_setup',x)];const r=await run({},x);assert.equal(r.state.currentSalesStage,'DISCOVERY');assert(r.delivery.quote);const c=build({text:'Okay',state:r.state,history:[{_id:'out',direction:'outbound',status:'sent',text:r.response,sentAt:new Date().toISOString(),automation:{question:r.question,delivery:r.delivery}}]});require('./delivery').reconcile(r.state.core,c);assert.equal(states.projection(r.state.core).currentSalesStage,'PRICE_PRESENTED');});
test('failed or queued response cannot become delivery evidence',()=>{const core=states.initial({});for(const status of ['queued','failed','unknown']){const c=build({text:'x',history:[{_id:status,direction:'outbound',status,text:'quote',automation:{delivery:{selectionVersion:0,stage:'PRICE_PRESENTED'}}}]});require('./delivery').reconcile(core,c);}assert.equal(core.delivered.stage,undefined);});
test('benign credential discussion retains meaning but values are redacted',()=>{assert.equal(build({text:'Will I need to share my password?'}).messages[0].text,'Will I need to share my password?');const text=build({text:'My password is secret123 and I need TikTok setup.'}).messages[0].text;assert(!text.includes('secret123'));assert(text.includes('TikTok setup'));});
test('long-message tail survives context and oversized turn is explicit',async()=>{const text='a'.repeat(7000)+' Actually Meta';assert.equal(build({text}).messages[0].text,text);const x=interpretation('a'.repeat(24001));const r=await run({},x);assert.equal(r.phases.length,0);assert.match(r.error,/no truncation/);});
test('unknown-budget answer deactivates actual sent budget question',()=>{const x=interpretation('I do not know, suggest a budget');x.value.recommendations=[{text:'budget advice',evidence:x.evidence}];const q={_id:'actual',direction:'outbound',status:'sent',text:'What daily budget?',sentAt:new Date().toISOString(),automation:{question:{purpose:'BUDGET',fields:['budget']}}};const c=build({messages:[{_id:x.id,text:x.evidence.text}],history:[q]});const s=states.merge(seed(),x.value,c,records).state;assert.equal(build({text:'Next',state:{core:s},history:[q]}).pendingQuestion,null);});

test('typed package selection uses inclusive catalogue total exactly once',async()=>{const x=interpretation('I choose the 60k package');x.value.items=[item('tiktok','ads_management',x)];x.value.budgets=[budget('PACKAGE_SELECTION',60000,x,'tiktok:ads_management')];const r=await run({},x);assert.equal(r.amount,60000);assert.equal(r.state.core.quote.items[0].breakdown.managementFee,25000);assert.equal(r.state.core.quote.items[0].breakdown.advertisingBudget,35000);});
test('counteroffer is neither accepted ad spend nor a discount',async()=>{const x=interpretation('Can you take 50k?');x.value.items=[item('tiktok','ads_management',x)];x.value.budgets=[budget('COUNTEROFFER',50000,x)];const r=await run({},x);assert.equal(r.amount,null);assert.equal(r.state.budget,undefined);assert.match(r.response,/not negotiable/);});
test('all-in and daily budgets project without stale legacy budget meanings',async()=>{let x=interpretation('Manage TikTok for seven days daily');x.value.items=[item('tiktok','ads_management',x)];x.value.budgets=[budget('DAILY_AD_SPEND',5000,x,'tiktok:ads_management')];x.value.facts=[fact('duration',7,x,'tiktok:ads_management')];let r=await run({},x);assert.equal(r.state.budget,5000);assert.equal(r.state.budgetBasis,'daily');x=interpretation('Actually total cap including everything');x.value.budgets=[budget('ALL_IN_CAP',100000,x,'tiktok:ads_management')];r=await run(r.state,x);assert.equal(r.state.budget,undefined);assert.equal(r.state.budgetBasis,undefined);assert.equal(r.state.allInCap,100000);assert.equal(r.state.duration,7);});
test('switching purchase paths does not leak budgets and preserves negative decisions',()=>{let x=interpretation('Advertising cap');x.value.budgets=[budget('ALL_IN_CAP',100000,x)];let s=merge(seed(),x);x=interpretation('Course instead');x.value.purchaseChange={action:'select',path:'course',evidence:x.evidence};s=merge(s,x);assert.equal(s.core.purchaseBudget,undefined);x=interpretation('Back to advertising');x.value.purchaseChange={action:'resume',path:'advertising',evidence:x.evidence};s=merge(s,x);assert.equal(s.core.purchaseBudget.amount,100000);assert.equal(s.customerWantsToProceed,false);});
test('legacy negative hold survives without trusting historical yes slots',()=>{const old=seed();delete old.core.schemaVersion;old.core.readiness='deferred';old.core.facts['global:proceed']={status:'CONFIRMED',value:'yes'};const core=states.initial(old);assert.equal(consent.effective(core).blocked,true);});
test('legacy many-by-many relationships require clarification',async()=>{const old=seed();delete old.core.schemaVersion;old.core.items=['tiktok','meta'].flatMap(platform=>['account_setup','ads_management'].map(type=>({id:`${platform}:${type}`,type,platform})));const r=await run(old,interpretation('Continue'));assert.equal(r.question.purpose,'RELATIONSHIPS');assert.equal(r.state.core.items.length,0);assert.equal(r.state.core.legacy.items.length,4);});
test('unaccepted request cannot be recorded as an executed selection',async()=>{const x=interpretation('A choice');x.value.items=[{...item('tiktok','account_setup',x),confidence:.1}];x.value.requests=[need('select_service',x)];const r=await run({},x);assert.notEqual(r.debug.requestLedger[0].disposition,'ACTIONED');assert.equal(r.state.core.items.length,0);});
test('later support reply preserves the last meaningful delivered stage',()=>{const core=states.initial({});require('./delivery').reconcile(core,{sentEffects:[{id:'price',sentAt:'2026-10-06T01:00:00Z',effect:{selectionVersion:0,stage:'PRICE_PRESENTED'}},{id:'support',sentAt:'2026-10-06T01:01:00Z',effect:{selectionVersion:0,stage:null}}]});assert.equal(core.delivered.stage,'PRICE_PRESENTED');assert.equal(core.delivered.outboundMessageId,'price');});
test('quoted multiword credentials are redacted without losing service question',()=>{const text=build({text:'My password is "two secret words". How does setup work?'}).messages[0].text;assert(!text.includes('secret words'));assert(text.includes('How does setup work?'));});
test('V2 invoice wording only uses trusted invoice fields',()=>{const text=require('../invoices').trustedPaymentText({amount:20000,accountNumber:'1234567890',bankName:'Provider Bank',accountName:'Approved Checkout'},'https://approved.example/invoice');assert.match(text,/20,000/);assert.match(text,/1234567890/);assert.match(text,/approved.example/);assert.doesNotMatch(text,/Payment confirmed|Payment received/);});
test('repeating an unchanged typed budget does not revoke valid current consent',()=>{let x=interpretation('Manage TikTok at daily budget');x.value.items=[item('tiktok','ads_management',x)];x.value.budgets=[budget('DAILY_AD_SPEND',5000,x,'tiktok:ads_management')];let s=merge({},x);x=interpretation('Send payment details');x.value.decisions=[event('PAYMENT_REQUESTED',x)];s=merge(s,x);const version=s.core.selectionVersion;x=interpretation('Yes same daily budget');x.value.budgets=[budget('DAILY_AD_SPEND',5000,x,'tiktok:ads_management')];s=merge(s,x);assert.equal(s.core.selectionVersion,version);assert.equal(s.paymentDetailsRequested,true);});
test('explicit item selection answers the actual sent service choice',()=>{const x=interpretation('Set up TikTok');x.value.items=[item('tiktok','account_setup',x)];const c=build({messages:[{_id:x.id,text:x.evidence.text}],history:[{_id:'question',direction:'outbound',status:'sent',text:'Choose a service',automation:{question:{purpose:'SERVICE',fields:['services'],choices:[{label:'Setup',value:'account_setup'}]}}}]});const s=states.merge({},x.value,c,records).state;assert.equal(s.answeredQuestions[0].id,'question');assert.equal(s.answeredQuestions[0].choices[0].value,'account_setup');assert.equal(s.answeredQuestions[0].active,false);});
test('validation repair rechecks the entire ledger, not only the last failed need',async()=>{const x=interpretation('Explain setup and requirements');x.value.requests=[need('ask_support_question',x),need('ask_requirements',x,'r2')];let calls=0;const r=await run(seed(),x,{prose:'Approved explanation.',grounding:input=>{calls++;assert(input.requestLedger.every(n=>n.disposition==='PENDING'));const proof=require('./fixtures').grounding(input);if(calls===1)proof.coverage=proof.coverage.slice(0,1);return proof;}});assert.equal(calls,2);assert.equal(r.action,'reply',r.error);});
test('a purchase cap also bounds independently selected item budgets',async()=>{const x=interpretation('My total cap and daily ads');x.value.items=[item('tiktok','account_setup',x),item('tiktok','ads_management',x)];x.value.budgets=[budget('ALL_IN_CAP',50000,x),budget('DAILY_AD_SPEND',5000,x,'tiktok:ads_management')];x.value.facts=[fact('duration',7,x,'tiktok:ads_management')];x.value.decisions=[event('PAYMENT_REQUESTED',x)];const r=await run({},x);assert.equal(r.action,'reply');assert.equal(r.question.purpose,'CAP');assert.equal(r.amount,null);});
