// Local deterministic rendering only. No model, network, or application imports.
const fs=require('node:fs'),path=require('node:path');
const load=f=>JSON.parse(fs.readFileSync(path.join(__dirname,f),'utf8'));
const totals=load('totals.json'),cases=fs.readdirSync(__dirname).filter(f=>/^G\d\d\.json$/.test(f)).sort().map(load);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notes=fs.existsSync(path.join(__dirname,'review-notes.json'))?load('review-notes.json'):{};
const all=cases.flatMap(c=>c.turns),metrics={...totals,completedTurns:all.filter(t=>t.status==='COMPLETED').length,providerFailures:all.filter(t=>t.status==='INCONCLUSIVE_PROVIDER').length,backendRejectedTurns:all.filter(t=>t.status==='BACKEND_REJECTED').length,toolCalls:all.flatMap(t=>t.result?.debug?.tools||t.debug?.tools||[]).length,knowledgeRetrievalCalls:all.flatMap(t=>t.knowledge||[]).length,safetyFindings:all.flatMap(t=>t.safetyFailures),simulatedActions:all.flatMap(t=>t.simulatedActions),rawModelVersions:[...new Set(all.flatMap(t=>t.rawResponses.map(r=>r.model)))]};
let html=`<!doctype html><html><head><meta charset="utf-8"><title>V3 Golden Evaluation — 7 October 2026</title><style>body{font:16px/1.55 system-ui;max-width:1100px;margin:40px auto;padding:0 24px;color:#18263d;background:#f5f7fb}article,header{background:white;border:1px solid #dce3ed;padding:24px;border-radius:14px;margin:20px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 monospace;background:#edf1f7;padding:14px}blockquote{white-space:pre-wrap;border-left:4px solid #5478bb;margin:12px 0;padding:10px 18px;background:#f2f6ff}.customer{border-color:#23a080;background:#effbf7}.bad{color:#a42626}details{margin:12px 0}a{color:#244faa}.metrics{font-weight:600}.turn{border-top:1px solid #dce3ed;padding:18px 0}</style></head><body><header><h1>V3 golden evaluation</h1><p>30 prepared conversations, one pass, one configured model, no independent LLM judge. No fixes made during evaluation.</p><p class="metrics">Model: ${esc(totals.model)} · Model API calls: ${totals.totals.calls} · All OpenAI HTTP calls including context: ${totals.totals.http_calls}<br>Input: ${totals.totals.input_tokens.toLocaleString()} · Cached input: ${totals.totals.cached_input_tokens.toLocaleString()} · Output: ${totals.totals.output_tokens.toLocaleString()} · Total: ${totals.totals.total_tokens.toLocaleString()}<br>Estimated cost: $${totals.totals.estimated_cost_usd.toFixed(6)} USD</p><p>Cost uses standard gpt-4.1-mini input $0.40, cached $0.10, output $1.60 per million tokens. Estimate excludes taxes. <a href="https://developers.openai.com/api/docs/models/gpt-4.1-mini">Official pricing</a>.</p><p>Only synthetic customer messages and read-only approved business data were sent. Production plan_15 remains285000; local evaluation copy uses owner-approved265000. Calculator unchanged. G30 expected outcome updated for that correction, customer turns unchanged.</p><p>COMPLETED means the backend returned a reply, NOT that it answered correctly. Provider errors are inconclusive. Safety checks are limited deterministic backstops, not proof of semantic safety. Read the actual responses.</p><p>Simulation matches current Test behavior: no real financial/assignment ports; pending fixture for G23. Handoff intent does not lock subsequent test turns. Simulated invoice intent does not create a persistent invoice. These limitations affect payment journeys.</p><details><summary>Totals and audit metadata</summary><pre>${esc(JSON.stringify(metrics,null,2))}</pre></details><nav>${cases.map(c=>`<a href="#${c.id}">${c.id}</a>`).join(' · ')}</nav></header>`;
for(const c of cases){html+=`<article id="${c.id}"><h2>${c.id}: ${esc(c.category)}</h2><p>Expected: ${esc(c.expected.join(' '))}</p><p>Review: ${esc(notes[c.id]||'Manual owner review pending; no automatic semantic pass assigned.')}</p><p>Cost $${c.usage.estimated_cost_usd.toFixed(6)} · ${c.usage.calls} model calls · ${c.usage.input_tokens} input / ${c.usage.output_tokens} output / ${c.usage.total_tokens} total tokens</p>`;
for(const [n,t]of c.turns.entries()){const trace=t.result?.debug?.tools||t.debug?.tools||[];html+=`<section class="turn"><h3>Turn ${n+1} — ${esc(t.status)}</h3><blockquote class="customer">${esc(t.customer.map(m=>m.text).join('\n[rapid-message batch]\n'))}</blockquote><blockquote>${esc(t.result?.response||'[No final reply returned]')}</blockquote><p>Final action: ${esc(t.finalAction)} ${esc(t.result?.handoff||'')} · ${t.elapsedMs}ms · ${t.usage.calls} model calls · ${t.usage.input_tokens} input / ${t.usage.cached_input_tokens} cached / ${t.usage.output_tokens} output / ${t.usage.total_tokens} total · $${t.usage.estimated_cost_usd.toFixed(6)}</p>${t.error?`<pre class="bad">${esc(JSON.stringify(t.error,null,2))}</pre>`:''}<p>Tool calls: ${trace.length}; knowledge requests: ${t.knowledge.length}; simulated actions: ${t.simulatedActions.length}. Deterministic safety findings: ${t.safetyFailures.length}.</p><details><summary>Tools, arguments and results</summary><pre>${esc(JSON.stringify(trace,null,2))}</pre></details><details><summary>Knowledge records used</summary><pre>${esc(JSON.stringify(t.knowledge,null,2))}</pre></details><details><summary>Simulated actions and deterministic safety findings</summary><pre>${esc(JSON.stringify({actions:t.simulatedActions,safety:t.safetyFailures},null,2))}</pre></details><details><summary>Raw model outputs (including rejected responses)</summary><pre>${esc(JSON.stringify(t.rawResponses,null,2))}</pre></details><details><summary>History and state before/after, provider errors</summary><pre>${esc(JSON.stringify({history:t.historyBefore,before:t.stateBefore,after:t.stateAfter,providerErrors:t.providerErrors},null,2))}</pre></details></section>`;}html+='</article>';}
html+='</body></html>';
fs.writeFileSync(path.join(__dirname,'review.html'),html,{flag:'wx'});
fs.writeFileSync(path.join(__dirname,'summary.json'),JSON.stringify(metrics,null,2),{flag:'wx'});
console.log(JSON.stringify(metrics,null,2));
