// Offline report only. No API imports or calls; leaves all raw run artifacts intact.
const fs=require('node:fs'),path=require('node:path');
const read=n=>JSON.parse(fs.readFileSync(path.join(__dirname,n),'utf8'));
const write=(n,x)=>fs.writeFileSync(path.join(__dirname,n),typeof x==='string'?x:JSON.stringify(x,null,2),{flag:'wx'});
const all=Array.from({length:6},(_,i)=>read(`S${i+1}.json`)),totals=read('totals.json');
function parse(s){try{return JSON.parse(s);}catch{return {unparsed:s};}}
function analyze(t){
 const responseCalls=t.http.filter(h=>h.path==='/responses');
 const outputs=new Map();
 for(const h of responseCalls)for(const i of Array.isArray(h.body?.input)?h.body.input:[])if(i.type==='function_call_output')outputs.set(i.call_id,parse(i.output));
 const functions=responseCalls.flatMap((h,index)=>(h.response?.output||[]).filter(o=>o.type==='function_call').map(o=>({callId:o.call_id,name:o.name,args:parse(o.arguments),result:outputs.get(o.call_id)||null,modelCall:index+1})));
 const last=functions.at(-1);if(last&&!last.result&&t.error)last.result={ok:false,error:t.error.message,terminal:true};
 const attempts={};for(const c of functions){attempts[c.name]=(attempts[c.name]||0)+1;c.attempt=attempts[c.name];c.correctionAttempt=c.attempt>1&&functions.some(x=>x.name===c.name&&x!==c&&x.modelCall<c.modelCall&&x.result?.ok===false);}
 const candidates=functions.filter(c=>c.name==='finish_response').map(c=>({...c,originalCandidate:c.args.text,validatorReason:c.result?.ok===false?c.result.error:null,followingModelCalls:responseCalls.length-c.modelCall,finalResponse:t.result?.response||null,numericClassification:t.id==='S3.1'?'Customer-supplied budget plus non-financial duration; repaired candidate still contains raw duration':t.id==='S4.1'?'Correct calculator financial amounts plus non-financial duration/creative count':t.id==='S2.2'?'Correct catalogue amounts plus non-financial duration and word two':t.id==='S5.1'?'Correct configured package amounts plus non-financial durations':'See candidate and source data'}));
 const plan=t.plan||functions.filter(c=>c.name==='plan_turn').at(-1)?.args;
 const factual=plan?.requests?.some(r=>['business','price','recommendation'].includes(r.kind));
 return {id:t.id,functions,candidates,finalRepairCalls:candidates.filter(c=>c.validatorReason&&!c.result.terminal).length,modelClassifiedFactual:factual??null,requests:plan?.requests||[],retrieved:t.tools.filter(x=>['get_business_knowledge','get_service_details','get_services','resolve_service','get_recommended_ads_plans'].includes(x.tool)),finalSources:t.result?.debug?.coverage||[],skippedRetrievalReason:t.tools.length?null:t.error?.message||'No requested business retrieval',providerErrors:t.http.filter(h=>h.error).map(h=>({path:h.path,...h.error})),flags:[...t.safety,...(t.error?[t.error.message]:[])]};
}
const observations=all.flatMap(s=>s.turns.map(analyze));write('observations.json',observations);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=x=>`<pre>${esc(JSON.stringify(x,null,2))}</pre>`;
const notes=fs.existsSync(path.join(__dirname,'review-notes.json'))?read('review-notes.json'):{};
let html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Joshspot V3 focused smoke test</title><style>body{font:16px/1.55 system-ui;background:#f4f6fa;color:#19263b;margin:0}main{max-width:1080px;margin:auto;padding:32px 18px}h1{font-size:30px}h2{margin-top:36px}article,header{background:white;border:1px solid #dce3ee;border-radius:14px;padding:22px;margin:18px 0}.customer{background:#eaf1ff}.reply{background:#edf7ec}.bubble{padding:16px;border-radius:10px;white-space:pre-wrap;margin:12px 0}.bad{color:#a72a32}.meta{font-size:13px;color:#50617c}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f6fa;padding:12px;font-size:12px}summary{cursor:pointer;font-weight:600;margin:10px 0}a{color:#2359a4}nav{display:flex;flex-wrap:wrap;gap:14px}.note{border-left:4px solid #da9b26;padding:12px}table{border-collapse:collapse;width:100%}td,th{padding:9px;text-align:left;border-bottom:1px solid #ddd}</style><main><header><h1>V3 · focused real-model smoke test</h1><p>Six fresh scenarios, one attempt each. No fixes, judge, model comparison or production changes.</p><p class="note">Errors terminate a scenario. Unreached turns are shown explicitly; they are not counted as passed. Read these transcripts before deciding any next step.</p><nav>${all.map(s=>`<a href="#${s.id}">${s.id}</a>`).join('')}</nav><details><summary>Usage and integrity</summary>${json(totals)}</details></header>`;
for(const s of all){html+=`<section id="${s.id}"><h2>${esc(s.id+' · '+s.title)}</h2><p>${esc(notes[s.id]||'')}</p><details><summary>Frozen expected principles</summary>${json(s.expected)}</details>`;
 for(const t of s.turns){const o=observations.find(x=>x.id===t.id);html+=`<article><h3>${esc(t.id)} · ${esc(t.status)}</h3><div class="bubble customer"><b>Customer</b>\n${esc(t.customer.text)}</div><div class="bubble reply"><b>Final V3 response</b>\n${esc(t.result?.response||'[No final response — turn stopped]')}</div>${t.error?`<p class="bad">${esc(t.error.message)}</p>`:''}<p>${esc(notes[t.id]||'')}</p><p class="meta">${t.usage.calls} model calls · ${t.httpCalls} HTTP calls · ${t.modelIterations} loop iterations · ${(t.elapsedMs/1000).toFixed(2)} s · ${t.usage.input_tokens} input (${t.usage.cached_input_tokens} cached) / ${t.usage.output_tokens} output / ${t.usage.total_tokens} total tokens · $${t.usage.estimated_cost_usd.toFixed(6)}</p><details><summary>Purchase context before / after</summary>${json({before:t.stateBefore.purchase,after:t.stateAfter.purchase,quote:t.stateAfter.quote})}</details><details><summary>Requests, selected sources and actual retrieved records</summary>${json({requests:o.requests,retrieved:o.retrieved,finalSources:o.finalSources,skippedReason:o.skippedRetrievalReason})}</details><details><summary>All model tool calls, validation and correction attempts</summary>${json(o.functions)}</details><details><summary>Backend business-tool results and simulated actions</summary>${json({tools:t.tools,actions:t.simulatedActions})}</details><details><summary>Original final-response candidates and repairs</summary>${json(o.candidates)}</details><details><summary>Safety/provider findings</summary>${json({flags:o.flags,providerErrors:o.providerErrors})}</details><a href="${esc(t.id.replace('.','-turn-'))}.json">Raw turn trace</a></article>`;}
 if(s.notRun.length)html+=`<article><h3>Not run after ${esc(s.stopReason)}</h3><ol>${s.notRun.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article>`;html+='</section>';
}
html+='</main></html>';write('HUMAN-REVIEW.html',html);
console.log(JSON.stringify({turns:observations.length,toolCalls:observations.reduce((n,o)=>n+o.functions.length,0),knowledgeCalls:observations.reduce((n,o)=>n+o.retrieved.filter(r=>r.tool==='get_business_knowledge').length,0),candidateRejections:observations.flatMap(o=>o.candidates).filter(c=>c.validatorReason).map(c=>({reason:c.validatorReason,text:c.originalCandidate,extra:c.followingModelCalls})),providerErrors:observations.flatMap(o=>o.providerErrors)},null,2));
