const escape = value => String(value ?? "").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
module.exports = invoice => {
  const number = `JSM-${String(invoice._id).toUpperCase()}`;
  const amount = new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(invoice.amount);
  const date = invoice.paidAt ? new Date(invoice.paidAt).toLocaleString('en-GB',{timeZone:'Africa/Lagos',dateStyle:'long',timeStyle:'short'})+' (Lagos)' : 'Not recorded';
  const service = invoice.product === 'whatsapp-course' ? 'WhatsApp Status ads course' : invoice.product === 'ads-course' || (invoice.note || '').startsWith('Course purchase - WhatsApp:') ? 'TikTok, Facebook & Instagram ads course' : invoice.note || 'Invoice payment';
  const details = [['Receipt number',number],['Customer',invoice.customerName || 'Customer'],['Email',invoice.customerEmail],['Payment date',date],['Payment reference',invoice.reference || 'Not recorded']];
  return {subject:`Your payment receipt · Joshspot Media · ${number}`,
    text:`JOSHSPOT MEDIA\nPAYMENT RECEIPT — PAID\n\n${details.map(([k,v])=>`${k}: ${v}`).join('\n')}\n\nDescription: ${service}\nAmount received: ${amount}\nCurrency: NGN\n\nThank you for your payment. Please retain this receipt for your records.\nhttps://joshspotmedia.com`,
    html:`<!doctype html><html><body style="margin:0;background:#f1f4f8;padding:24px 12px;font-family:Arial,sans-serif;color:#192b38"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;margin:auto;background:white;border:1px solid #dce4eb;border-radius:16px"><tr><td style="background:#142f28;color:white;padding:32px"><div style="font-size:12px;letter-spacing:3px">JOSHSPOT MEDIA</div><h1 style="font-size:30px;margin:18px 0 8px">Payment receipt</h1><span style="color:#d0f5b4;font-size:12px;font-weight:bold">● PAID IN FULL</span></td></tr><tr><td style="padding:30px"><p style="font-size:14px;line-height:1.7">Thank you, ${escape(invoice.customerName || 'customer')}. We have received your payment.</p><table width="100%" cellspacing="0" cellpadding="0">${details.map(([k,v])=>`<tr><td style="padding:10px 8px 10px 0;color:#5a6b77;font-size:12px;vertical-align:top">${k}</td><td style="padding:10px 0;font-size:13px;overflow-wrap:anywhere">${escape(v)}</td></tr>`).join('')}</table><table width="100%" cellspacing="0" cellpadding="0" style="margin-top:24px;border-top:2px solid #192b38"><tr><th align="left" style="padding:16px 0;font-size:12px;color:#5a6b77">DESCRIPTION</th><th align="right" style="font-size:12px;color:#5a6b77">AMOUNT</th></tr><tr><td style="padding:0 16px 20px 0;font-size:14px;line-height:1.6">${escape(service)}</td><td align="right" style="vertical-align:top;font-size:14px;white-space:nowrap">${escape(amount)}</td></tr></table><div style="background:#eef5e9;padding:22px;border-radius:10px"><span style="font-size:12px;color:#365443">TOTAL RECEIVED · NGN</span><div style="font-size:30px;font-weight:bold;color:#173e2b;margin-top:8px">${escape(amount)}</div></div><p style="font-size:12px;line-height:1.7;color:#5a6b77;margin-top:24px">Please retain this receipt for your records.</p><a href="https://joshspotmedia.com" style="color:#245b40;font-size:12px">joshspotmedia.com</a></td></tr></table></body></html>`};
};
