const fs=require('node:fs'),path=require('node:path'),s=require('./catalogue-snapshot.json');
const role=require('../../inbox/ai/v2/knowledge').role;
(async()=>{
 const vendor=await import('../../inbox/ai/vendor/adsPricingConfig.mjs');
 const plans=s.records.filter(r=>r.kind==='plan').map(r=>{const preset=vendor.adsPricingConfig.recommendationPresets.find(p=>p.duration===r.data.duration);const q=preset?vendor.calculateTotal({mode:'custom',advertisingBudget:preset.advertisingBudget,budgetType:'total',duration:preset.duration,requestedCreatives:1,creativeMode:'testing'}):null;return {key:r.key,configuredTotal:r.data.amount,recordRevision:r.revision,recordUpdatedAt:r.updatedAt,calculator:q&&{advertisingSpend:q.advertisingBudget,managementFee:q.managementFee,total:q.total},sources:{configured:`catalogue-snapshot.json records.${r.key}.data.amount`,advertisingSpend:'inbox/ai/vendor/adsPricingConfig.mjs recommendationPresets',managementFee:'same calculator getManagementFee()/calculateTotal(), reused by inbox/ai/pricing.js'},conflict:!!q&&q.total!==r.data.amount};});
 const text=r=>r.data.preferredResponse||r.data.answer||r.data.message||'';
 const byText={};for(const r of s.records){const t=text(r).trim().toLowerCase();if(t)(byText[t]||=[]).push(r.key);}
 const audit={configRevision:s.config.revision,recordCount:s.records.length,counts:Object.fromEntries([...new Set(s.records.map(r=>r.kind))].map(k=>[k,s.records.filter(r=>r.kind===k).length])),exactDuplicateText:Object.entries(byText).filter(([,keys])=>keys.length>1).map(([text,keys])=>({text,keys})),legacyEnabled:s.records.filter(r=>['response','workflow','tone'].includes(r.kind)).map(r=>({key:r.key,kind:r.kind,title:r.title,note:'Enabled legacy record; V2 does not run legacy response/workflow branches.'})),unexpandedStrict:s.records.filter(r=>r.data.responseMode==='STRICT'&&/\{\{/.test(text(r))).map(r=>({key:r.key,text:text(r),role:role(r),note:'Review role/eligibility: literal template is not necessarily a usable V2 response.'})),legacyHandoffAfterReply:s.records.filter(r=>r.data.handoffAfterReply===true).map(r=>({key:r.key,reason:r.data.handoffReason,wording:text(r),note:'Legacy flag is not the same as V2 forceHandoff. Potential configuration expectation mismatch.'})),strict:s.records.filter(r=>r.data.responseMode==='STRICT').map(r=>({key:r.key,role:role(r),text:text(r)})),overlapGroups:[['service_difference','setup_vs_management','choose_service','ads_service_clarification'],['setup_scope','tiktok_setup_information','meta_setup_information','setup_requirements'],['campaign_expectations','review_6ac33e30ba3cd7082113f310_1791180346395'],['payment_claim','payment_claim_information','receipt_review_information']],configConflict:{source:'config.data.instructions',text:'Service onboarding and access requirements must hand off to CSS immediately after the approved onboarding response.',note:'Stale relative to the requested pre-payment policy. V2 does not directly load this legacy instruction string into its phase prompts; report as dormant configuration conflict, not proof it caused a V2 handoff.'},plans,ownerDecision:plans.filter(p=>p.conflict).map(p=>({key:p.key,label:'OWNER DECISION REQUIRED',choices:['Keep calculator advertising spend and fee; explicitly update configured package total to calculator result.','Keep configured package total; explicitly approve revised spend/fee or calculator preset. Do not let the model decide.']}))};
 fs.writeFileSync(path.join(__dirname,'knowledge-audit.json'),JSON.stringify(audit,null,2),{flag:'wx'});console.log(JSON.stringify({counts:audit.counts,duplicates:audit.exactDuplicateText.length,plans:audit.plans,ownerDecision:audit.ownerDecision},null,2));
})().catch(e=>{console.error(e.message);process.exitCode=1;});
