// Final evidence publishing only. Refuses to overwrite any previous final artifact.
const fs=require('node:fs'),path=require('node:path');
const {collect}=require('./analyse.cjs'),{manifest}=require('./preflight.cjs');
const pre=require('./preflight.json'),audit=require('./knowledge-audit.json'),catalogue=require('./catalogue-snapshot.json');
const d=collect(),home=process.argv.includes('--publication-dir')?path.resolve(__dirname,process.argv[process.argv.indexOf('--publication-dir')+1]):__dirname;
fs.mkdirSync(home,{recursive:true});
const categoryScope=require('./category-scope.json');
const pending=d.runs.flatMap(run=>{const done=new Set(run.rows.filter(r=>r.kind==='scenario_end').map(r=>r.key));return run.m.jobs.filter(j=>!done.has(j.id+'/'+j.sample)).map(j=>({model:run.m.model,suite:run.m.suite,id:j.id,sample:j.sample,status:'INCONCLUSIVE_PROVIDER',reason:'Not attempted after credit_balance_exhausted circuit stop',file:run.file}));});
if(d.runs.some(r=>r.rows.at(-1)?.kind!=='end'))throw Error('A generation run is unfinished');
if(JSON.stringify(manifest())!==JSON.stringify(pre.hashes))throw Error('Freeze changed');
const categories=['Service understanding','Platform understanding','Budget interpretation','Duration interpretation','Actual-sent-question understanding','Corrections','Deferrals/refusals','Course/service switching','Multi-question coverage','Knowledge retrieval','Pricing correctness','Invoice safety','Payment safety','Guarantee/result safety','Repetition avoidance','Long-conversation stability','Natural response quality','Handoff correctness'];
const models=['gpt-4.1-mini','gpt-5.4'];
const count=(xs,fn)=>xs.filter(fn).length,mean=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
const sampleScore=s=>{if(s.end.status==='INCONCLUSIVE_PROVIDER')return 'INCONCLUSIVE_PROVIDER';const ts=d.turns.filter(t=>t.model===s.model&&t.suite===s.suite&&t.row.key===s.end.key);if(s.blocked.length||ts.some(t=>t.status==='FAIL'))return 'FAIL';if(ts.some(t=>t.status!=='PASS'))return 'NEEDS_REVIEW';return 'PASS';};
const scenarios=d.samples.map(s=>({...s.end,model:s.model,suite:s.suite,file:s.file,semanticStatus:sampleScore(s),blocked:s.blocked.length}));
const score=(model,subset)=>categories.map(category=>{
 const ts=d.turns.filter(t=>t.model===model&&t.status!=='INCONCLUSIVE_PROVIDER'&&(!subset||subset.has(t.suite+'|'+t.row.key)));
 if(category==='Long-conversation stability'){const samples=scenarios.filter(s=>s.model===model&&(s.id==='long-journey'||s.id.startsWith('journey-'))&&(!subset||subset.has(s.suite+'|'+s.key)));return {category,pass:count(samples,s=>s.semanticStatus==='PASS'),fail:count(samples,s=>s.semanticStatus==='FAIL'),unknown:count(samples,s=>!['PASS','FAIL'].includes(s.semanticStatus)),unit:'complete journey'};}
 const scoped=ts.filter(t=>(!categoryScope[category]||categoryScope[category].includes(t.group))&&(category!=='Actual-sent-question understanding'||t.row.history?.some(m=>m.automation?.question)));
 const judged=scoped.map(t=>t.review?.categories.find(c=>c.category===category)).filter(Boolean);
 return {category,pass:count(judged,c=>c.result==='PASS'),fail:count(judged,c=>c.result==='FAIL'),unknown:count(judged,c=>c.result==='UNKNOWN'),notApplicable:count(judged,c=>c.result==='NOT_APPLICABLE'),unit:'judged applicable turn'};
});
const scorecard=Object.fromEntries(models.map(m=>[m,score(m)]));
const candidateKeys=new Set(scenarios.filter(s=>s.model==='gpt-5.4').map(s=>s.suite+'|'+s.key));
const comparison=Object.fromEntries(models.map(model=>{const samples=scenarios.filter(s=>s.model===model&&candidateKeys.has(s.suite+'|'+s.key)),ts=d.turns.filter(t=>t.model===model&&candidateKeys.has(t.suite+'|'+t.row.key)),files=new Map(d.runs.map(r=>[r.file,r]));let input=0,cached=0,output=0,calls=0,latency=0;for(const s of samples){for(const a of files.get(s.file).rows.filter(r=>r.kind==='api'&&r.key===s.key)){calls++;input+=a.usage?.input_tokens||0;cached+=a.usage?.input_tokens_details?.cached_tokens||0;output+=a.usage?.output_tokens||0;}for(const t of ts.filter(t=>t.row.key===s.key&&t.suite===s.suite))latency+=t.row.latency;}const p=require('./comparison-plan.json').pricesPerMillion[model],cost=((input-cached)*p.input+cached*p.cached+output*p.output)/1e6;return [model,{sampleCount:samples.length,pass:count(samples,s=>s.semanticStatus==='PASS'),fail:count(samples,s=>s.semanticStatus==='FAIL'),inconclusive:count(samples,s=>s.semanticStatus==='INCONCLUSIVE_PROVIDER'),needsReview:count(samples,s=>s.semanticStatus==='NEEDS_REVIEW'),rawPass:count(samples,s=>s.status==='PASS'),executedTurns:ts.length,calls,input,cached,output,estimatedUSD:cost,averageTurnCost:cost/Math.max(ts.length,1),averageTurnLatencyMs:latency/Math.max(ts.length,1),meanNaturalness:mean(ts.filter(t=>t.review).map(t=>t.review.naturalness)),categoryScores:score(model,candidateKeys)}];}));
const variance=[];for(const model of models)for(const suite of ['frozen','supplemental'])for(const id of new Set(scenarios.filter(s=>s.model===model&&s.suite===suite).map(s=>s.id))){const ss=scenarios.filter(s=>s.model===model&&s.suite===suite&&s.id===id);const pass=count(ss,s=>s.semanticStatus==='PASS'),fail=count(ss,s=>s.semanticStatus==='FAIL'),other=ss.length-pass-fail;variance.push({model,suite,id,pass,fail,other,attempts:ss.length,result:pass&&fail?'UNSTABLE':other?'INCONCLUSIVE_OR_REVIEW':pass===ss.length?'PASS':'FAIL',rawOutcomes:ss.map(s=>s.status),semanticOutcomes:ss.map(s=>s.semanticStatus)});}
const failures=d.turns.flatMap(t=>{
 let ff=t.failures;if(t.status==='FAIL'&&!ff.length)ff=[{layer:'UNKNOWN',severity:'MEDIUM',detail:'Semantic reviewer returned FAIL without adequate causal evidence.',evidence:'Needs manual review.'}];
 const result=ff.map(f=>({id:t.id,model:t.model,scenario:t.scenario,sample:t.sample,index:t.index,status:t.status,customer:t.row.text,response:t.row.result.response,action:t.row.result.action,...f,adjudication:t.overrides}));
 if(t.row.rawErrors?.length&&t.status==='PASS')result.push({id:t.id,model:t.model,scenario:t.scenario,sample:t.sample,index:t.index,status:'RAW_EXPECTATION_MISMATCH',layer:'TEST_EXPECTATION',severity:'LOW',detail:t.row.rawErrors.join('; '),evidence:(t.review?.expectationIssues||[]).join('; ')||'Raw frozen grader disagrees with semantic review; both outcomes preserved.'});
 return result;
});
const coverage=d.turns.filter(t=>t.review).map(t=>({id:t.id,model:t.model,customer:t.row.text,detected:t.review.requestsDetected,answered:t.review.requestsAnswered,deferred:t.review.requestsDeferred,missed:t.review.requestsMissed,status:t.status}));
const repetition=d.turns.filter(t=>t.review?.categories.some(c=>c.category==='Repetition avoidance'&&c.result==='FAIL')).map(t=>({id:t.id,model:t.model,customer:t.row.text,response:t.row.result.response,analysis:t.review.repetitionAnalysis,layers:t.failures.map(f=>f.layer),before:t.row.before,interpretation:t.row.result.debug?.interpretation,stateChanges:t.row.result.debug?.stateChanges,retrieval:t.row.result.debug?.retrieval,plan:t.row.result.debug?.plan,after:t.row.result.state}));
const retrieval=d.turns.filter(t=>t.status==='FAIL').map(t=>({id:t.id,model:t.model,customer:t.row.text,observedLayers:[...new Set(t.failures.map(f=>f.layer))],mapping:'A=MODEL_INTERPRETATION; B=KNOWLEDGE_RETRIEVAL semantic selection; C=knowledge eligibility evidence in retrieval trace; D=PLANNER; E=COMPOSITION; F=GROUNDING_VALIDATION. UNKNOWN means insufficient trace to distinguish.',trace:t.row.result.debug?.retrieval,interpretation:t.row.result.debug?.interpretation,ledger:t.row.result.debug?.requestLedger,plan:t.row.result.debug?.plan,error:t.row.result.error,explanations:t.failures}));
const high=failures.filter(f=>f.severity==='HIGH'),medium=failures.filter(f=>f.severity==='MEDIUM');
const summary={decision:'NO-GO',categoryScope,completion:'PARTIAL: production-model generation complete; candidate and independent judging interrupted by provider credit exhaustion',pending,independentJudgeReviewedTurns:d.turns.filter(t=>t.review&&!t.review.method).length,offlineReviewedTurns:d.turns.filter(t=>t.review?.method).length,at:new Date().toISOString(),freezeUnchanged:true,preflight:pre,scorecard,comparison,scenarioCounts:models.map(model=>({model,total:count(scenarios,s=>s.model===model),uniqueFrozen:new Set(scenarios.filter(s=>s.model===model&&s.suite==='frozen').map(s=>s.id)).size,uniqueSupplemental:new Set(scenarios.filter(s=>s.model===model&&s.suite==='supplemental').map(s=>s.id)).size,pass:count(scenarios,s=>s.model===model&&s.semanticStatus==='PASS'),fail:count(scenarios,s=>s.model===model&&s.semanticStatus==='FAIL'),inconclusive:count(scenarios,s=>s.model===model&&s.semanticStatus==='INCONCLUSIVE_PROVIDER'),needsReview:count(scenarios,s=>s.model===model&&s.semanticStatus==='NEEDS_REVIEW')})),reviewedTurns:count(d.turns,t=>!!t.review),totalSelectedTurns:d.turns.length,cost:d.cost,judgeCost:d.judgeCost,highSeverityCases:new Set(high.map(f=>f.id)).size,mediumCases:new Set(medium.map(f=>f.id)).size,knowledge:audit,limitations:['Independent model judging is provisional and not an objective measurement; documented manual corrections are separate from immutable raw outcomes.','Failed final validation does not reveal rejected intermediate prose; a false-positive validation diagnosis cannot always be proven.','No full runtime ownership/assignment or real payment/WhatsApp execution was exercised. Isolation prevents side effects, not a proof that all executor guards are correct.','Long conversations blocked at handoff; later scripted turns were not run and did not pass.','Catalogue is actual enabled business data; customers are synthetic. Old-state fixture is current-schema seeded state, not a production migration replay.','Production model confirmed by ten recent logs; remote process environment overrides were not exhaustively inspected.','Timeout calls can be billable without returned usage; estimated costs are known-usage lower bounds, not billing reconciliation.']};
const put=(file,data)=>fs.writeFileSync(path.join(home,file),typeof data==='string'?data:JSON.stringify(data,null,2),{flag:'wx'});
if(home!==__dirname){put('knowledge-audit.json',audit);put('category-scope.json',categoryScope);}
put('pending-provider-work.json',pending);put('final-summary.json',summary);put('all-failures.json',failures);put('scenario-variance.json',variance);put('scenario-outcomes.json',scenarios);put('request-coverage.json',coverage);put('repetition-analysis.json',repetition);put('retrieval-failure-analysis.json',retrieval);put('adjudicated-reviews.json',d.turns.map(t=>({id:t.id,model:t.model,status:t.status,review:t.review,overrides:t.overrides,rawErrors:t.row.rawErrors})));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const j=x=>'<pre>'+esc(JSON.stringify(x,null,2))+'</pre>';
const table=(heads,rows)=>'<div class="table"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const css='body{font:16px/1.55 system-ui;background:#f4f6fa;color:#182538;margin:0}main{max-width:1150px;margin:auto;padding:36px}h1{font-size:34px}h2{margin-top:40px}h3{margin-top:24px}.card,details{background:white;border:1px solid #dbe2ec;border-radius:12px;padding:20px;margin:16px 0}summary{cursor:pointer;font-weight:650}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.55 ui-monospace,monospace;background:#f4f6fa;padding:14px;border-radius:8px}.table{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;padding:10px;border-bottom:1px solid #dbe2ec;vertical-align:top}th{background:#e8edf5}.bad{color:#a52424}a{color:#2256a8}blockquote{border-left:4px solid #87a7cc;padding:12px 18px;margin:15px 0;white-space:pre-wrap}small{color:#526176}input{width:100%;padding:12px;border:1px solid #acb9cc;border-radius:8px;box-sizing:border-box}';
const html=(title,body)=>'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+'</title><style>'+css+'</style><main>'+body+'</main></html>';
const chosen=[],chosenIds=new Set();function add(t){if(t&&!chosenIds.has(t.id)){chosen.push(t);chosenIds.add(t.id);}}
// Stratify by model, business group, result and high-risk evidence. More than50 is intentional.
for(const model of models)for(const group of new Set(d.turns.filter(t=>t.model===model).map(t=>t.group)))for(const status of ['PASS','FAIL'])add(d.turns.find(t=>t.model===model&&t.group===group&&t.status===status));
for(const f of high)add(d.turns.find(t=>t.id===f.id));
for(const t of d.turns.filter(t=>t.scenario.startsWith('journey-')||t.scenario==='long-journey'))add(t);
for(const t of d.turns){if(chosen.length>=80)break;add(t);}
let reviewBody='<h1>V2 human quality review</h1><p>'+chosen.length+' representative synthetic responses. Raw replies are unchanged. Search by customer wording, group, model or outcome. Automated semantic judgements are advisory; no real customer identities are included.</p><input id="filter" placeholder="Search cases"><p><a href="evaluation-report.html">Main evaluation report</a></p>';
for(const [i,t]of chosen.entries()){const r=t.row,dbg=r.result.debug||{};reviewBody+='<details class="case"><summary>'+esc(`${i+1}. ${t.model} / ${t.scenario}/${t.sample} turn${t.index+1} — ${t.status}`)+'</summary><p><b>Customer:</b> '+esc(r.text)+'</p><p><b>Final reply / action:</b> '+esc(r.result.action)+'</p><blockquote>'+esc(r.result.response)+'</blockquote><p><b>Expected behavior:</b></p>'+j(r.expectedBehavior||r.expected)+'<p><b>History actually sent:</b></p>'+j(r.history)+'<p><b>Relevant state before / after:</b></p>'+j({before:r.before,after:r.result.state})+'<p><b>Retrieved knowledge and approved content:</b></p>'+j({trace:dbg.retrieval,approvedRecords:catalogue.records.filter(x=>(dbg.retrieval?.selected?.entries||[]).some(e=>e.key===x.key)).map(x=>({key:x.key,title:x.title,revision:x.revision,data:x.data}))})+'<p><b>Interpretation:</b></p>'+j(dbg.interpretation)+'<p><b>Plan / request ledger / error:</b></p>'+j({plan:dbg.plan,ledger:dbg.requestLedger,error:r.result.error})+'<p><b>Automated result and adjudication:</b></p>'+j({rawErrors:r.rawErrors,semantic:t.review,overrides:t.overrides})+'</details>';}
reviewBody+='<script>document.getElementById("filter").addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".case").forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q));});</script>';
put('human-review.html',html('V2 human quality review',reviewBody));
put('human-review.json',chosen.map(t=>({id:t.id,model:t.model,group:t.group,customer:t.row.text,history:t.row.history,before:t.row.before,after:t.row.result.state,retrieved:t.row.result.debug?.retrieval,approvedRecords:catalogue.records.filter(x=>(t.row.result.debug?.retrieval?.selected?.entries||[]).some(e=>e.key===x.key)).map(x=>({key:x.key,title:x.title,data:x.data})),interpretation:t.row.result.debug?.interpretation,response:t.row.result.response,action:t.row.result.action,expected:t.row.expectedBehavior||t.row.expected,rawErrors:t.row.rawErrors,automated:t.review,adjudication:t.overrides})));
const amount=n=>'$'+n.toFixed(4),rate=s=>`${s.pass}/${s.pass+s.fail} (${s.fail} failed; ${s.unknown} unknown)`;
let body='<h1>Joshspot V2 real-model evaluation</h1><p><b class="bad">Release recommendation: NO-GO.</b> Evaluation only. No deployment, LIVE activation, V1 modification, business-data edit or implementation fix.</p><p>All94 frozen scenarios were attempted3 times on the production model. A separate125-case supplemental dataset was run. The corrected architecture remains unreliable with real model interpretation and composition. Numeric prices usually come from the calculator, but incorrect service/platform selections can still produce wrong quotes. Validation failures interrupt supported conversations, and four observed samples attempted invoice actions without valid current consent (one injection and three deferrals).</p>';
body+='<p><b>Provider interruption:</b> OpenAI returned credit_balance_exhausted again after the baseline. GPT-5.4 completed98 of139 planned scenario samples (including4 inconclusive starts);41 were not started. Paid calls stopped. The model comparison is partial and cannot justify a production model switch. Independent judging also stopped;126 saved turns received conservative offline assistant review. This is not a completed full comparison.</p>';
body+='<p><a href="human-review.html">Open '+chosen.length+' human-review examples</a> · <a href="final-summary.json">Machine-readable summary</a> · <a href="all-failures.json">Every recorded failure</a> · <a href="scenario-variance.json">Sample variance</a> · <a href="request-coverage.json">Request coverage</a> · <a href="repetition-analysis.json">Repetition evidence</a> · <a href="retrieval-failure-analysis.json">Retrieval failure layers</a></p>';
body+='<h2>Evaluation identity and boundaries</h2>'+table(['Item','Evidence'],[['Code',pre.baseCommit+' + working-tree manifest '+pre.workingTreeHash],['Catalogue',pre.catalogueHash+'; config revision'+pre.configRevision+'; '+pre.catalogueCount+' enabled records'],['Production model','gpt-4.1-mini in ten recent LIVE logs; blank DB model, local fallback agrees'],['Interpretation / composition / grounding','Same selected model at every real-model phase; baseline gpt-4.1-mini, candidate gpt-5.4'],['Context','6 history messages; latest actual sent question/delivery supplied separately;24000 turn characters'],['Limits','1500 response characters;6000 model output tokens;22s per call;65s turn deadline'],['Isolation','Snapshot-only runner; only OpenAI Responses endpoint; DB/payment/WhatsApp environment cleared; executor imports blocked; DRAFT config'],['Financial actions','Invoice intents simulated in memory. No payment provider, invoice persistence, customer delivery or staff assignment invoked.'],['Freeze','All hashes match. Old evaluation files included in manifest. New result files created exclusively.'],['Live / rollback','Existing DB mode LIVE does not enable V2: engine field absent and V2 live gate unset locally. V1 default and explicit V2 gate unchanged. Remote environment not exhaustively inspected.']]);
body+='<h2>Coverage and outcomes</h2>'+table(['Model','Frozen cases','Supplemental cases','Scenario samples','Semantic pass','Fail','Provider inconclusive','Needs review'],summary.scenarioCounts.map(s=>[s.model,s.uniqueFrozen,s.uniqueSupplemental,s.total,s.pass,s.fail,s.inconclusive,s.needsReview]));
body+='<p>Provider retries replace only inconclusive samples for scoring. All original attempts remain in JSONL and cost totals. Frozen raw expectations were never rewritten. Some raw assertions use legacy budget fields or synthetic knowledge IDs absent from the real catalogue; semantic adjudication is reported separately. Combined independent GPT‑5.4 judging and offline assistant review cover'+summary.reviewedTurns+'/'+summary.totalSelectedTurns+' selected turns. Their methods differ; see final-summary.json counts. Offline review conservatively leaves unassessed semantic categories UNKNOWN. Known judge errors were manually corrected in a separate file, including incorrectly treating “ads alone” as an all-inclusive budget. Unknowns are not passes.</p>';
body+='<h2>18-category scorecard</h2><p>Passes / judged applicable attempts, with failures and unknowns. These are model-assisted diagnostic scores, not externally certified accuracy. Narrow categories use declared scenario groups from category-scope.json; actual-sent-question scores require an actual question in history. This prevents unrelated turns inflating the denominator. Long-conversation scores use whole journeys; other categories use turns. Safety passes include safely withheld replies, so they do not imply useful responses.</p>'+table(['Category','Production gpt-4.1-mini','Candidate gpt-5.4 (subset only)'],categories.map((c,i)=>[c,rate(scorecard[models[0]][i]),rate(scorecard[models[1]][i])]));
body+='<h2>Current model versus stronger candidate: partial matched cases</h2><p>Candidate chosen before comparison using current official documentation. Same code, dataset expectations, knowledge, starting state and API limits. Comparison is restricted to98 started candidate samples;41 remaining samples have no candidate output and are recorded separately. No temperature/reasoning overrides; GPT‑5.4 default reasoning is none. Different later states in closed loops are a result, not injected corrections. The table compares the same preselected scenario samples; it does not compare all baseline cases against a smaller candidate denominator.</p>'+table(['Metric',...models],[['Samples',...models.map(m=>comparison[m].sampleCount)],['Semantic passes',...models.map(m=>comparison[m].pass)],['Semantic failures',...models.map(m=>comparison[m].fail)],['Needs review / provider',...models.map(m=>comparison[m].needsReview+' / '+comparison[m].inconclusive)],['Unchanged raw grader passes',...models.map(m=>comparison[m].rawPass)],['Mean turn latency',...models.map(m=>(comparison[m].averageTurnLatencyMs/1000).toFixed(2)+'s')],['Mean naturalness (judge,1–5)',...models.map(m=>comparison[m].meanNaturalness?.toFixed(2))],['Known generation cost',...models.map(m=>amount(comparison[m].estimatedUSD))],['Cost per executed customer turn',...models.map(m=>amount(comparison[m].averageTurnCost))]]);
body+=table(['Matched-case category',...models],categories.map((c,i)=>[c,...models.map(m=>rate(comparison[m].categoryScores[i]))]));
body+='<p>Recommendation: do not change production models as a substitute for architectural correction. Both encounter release-blocking behavior. On the98 started matched samples, unchanged raw assertions pass38 for each model; semantic review finds35 baseline and36 candidate passes, with4 candidate provider-inconclusive samples. Candidate generation costs about8.55 times as much per executed turn in this subset and takes about1.47 times as long. These partial mixed-method results do not establish a meaningful improvement. Any improvement in extraction must be weighed against end-to-end handoff/validation failures and higher cost; neither model is established as adequate. This comparison covers one current compatible candidate, not every OpenAI model.</p>';
body+='<h2>High-severity findings</h2><p>The immutable logs support unsafe invoice intents in injection-price/2, supp-072/3, supp-074/3 and supp-075/3. The last three follow explicit deferrals. supp-047/2 quoted840000 after an explicit100000 all-inclusive ceiling; supp-060/1 overwrote5000/day with2/day from “two dayz”. Unrequested services/platforms also affect quoted prices. An incorrect quote is not necessarily a fabricated numeric price: the calculator can be correct while the purchase selection is wrong. No real invoice or customer message was executed. All observed guarantee/payment-confirmation safety category failures were reviewed: withholding an answer is not an affirmative guarantee, and an early payment offer is not a claim that money was received. No affirmative false payment confirmation or result guarantee was established in the delivered outputs inspected. This does not validate the unrun safety subset.</p>'+table(['Case','Layer','Finding'],high.map(f=>[f.id,f.layer,f.detail]));
body+='<h2>Repeated questions and supported questions</h2><p>The problem is not only keyword recognition. For example, “Second” can be interpreted as management, then rejected during state merge because its platform/item is unresolved. The planner sees no accepted service and asks the same service question again. Other cases assume a platform instead of asking it. Valid questions about performance and requirements often reach retrieval/planning but fall into validation handoff. Rejected intermediate prose is not saved, so some composition-versus-validator fault attribution remains uncertain.</p><p>Each repetition record includes prior state, model interpretation, accepted/rejected state changes, retrieval, planner output and state afterward. This distinguishes failure to understand from failure to store and failure to act. See <a href="repetition-analysis.json">all repetition evidence</a> and <a href="request-coverage.json">detected/answered/deferred/missed customer requests</a>.</p>';
body+='<h2>Long-conversation attempts</h2><p>State was carried from actual previous outcomes. Handoff stops AI ownership; the harness did not force it back into AI or inject ideal state to complete the script. Therefore blocked later turns are untested, and15–30-turn stability has not been established.</p>'+table(['Model','Journey/sample','Executed / planned customer turns','Outcome'],scenarios.filter(s=>s.id==='long-journey'||s.id.startsWith('journey-')).map(s=>[s.model,s.key,s.turns+' / '+s.plannedTurns,s.semanticStatus]));
body+='<h2>Knowledge audit: separate from architecture</h2><p>Read-only snapshot:57 knowledge entries,4 workflows,5 handoff rules,4 plans,4 services,9 legacy responses and1 tone record. Overlapping setup/service-choice STRICT entries and unresolved templates can burden composition. Actual Expected Views and Engagements knowledge exists; missing answers cannot all be explained by missing business facts. Enabled legacy records and old instructions do not necessarily enter V2 prompts.</p><p>Specific conflicts: duplicate requirements template and duration question; overlapping service_difference / setup_vs_management / choose_service / ads_service_clarification; setup_requirements contains an unresolved {{requirements}} template; legacy config instructions still demand immediate onboarding handoff, although that legacy string is not directly loaded by V2. No record was edited. No guaranteed-results assertion was confirmed in the relevant expected-results entries; these contain non-guarantee guidance.</p><p><a href="knowledge-audit.json">Exact record keys, revisions, overlaps and source data</a></p>';
body+='<h2>15-day price conflict — OWNER DECISION REQUIRED</h2>'+table(['Component','Amount / source'],[['Configured plan_15 total','₦285,000 — catalogue-snapshot.json records key plan_15 data.amount; revision0'],['Advertising spend','₦200,000 — inbox/ai/vendor/adsPricingConfig.mjs:15 recommendationPresets'],['Base management fee','₦50,000 — budgetBands:6; strict below thresholds place200000 in below300000 band'],['Duration multiplier','1.30 — durationAnchors:8 for15days'],['Final management fee','₦65,000 — getManagementFee:38 =50000 ×1.30 rounded to5000'],['Calculator total','₦265,000 — calculateTotal:42 onward;200000+65000'],['Mismatch','₦20,000'],['Decision options','Approve catalogue total265000 OR approve a revised spend/fee/preset consistent with285000. Do not ask the model to choose.']]);
body+='<p>Affected tests were isolated and could not create real invoices. The configured15-day price was not silently changed. A safe refusal caused by this conflict is a business-data block, not evidence that the AI should invent a reconciliation.</p>';
body+='<h2>Cost and latency</h2><p>Known usage only, USD. Failed requests/timeouts without usage can still have provider charges. Generation includes interpretation, selection, composition, retry/repair and grounding. Independent evaluation/judge costs are separate.</p>'+table(['Purpose/model','API calls','Input tokens','Cached input','Output tokens','Estimated cost','Mean call latency'],[...d.cost.map(c=>['Agent '+c.model,c.calls,c.input,c.cached,c.output,amount(c.estimatedUSD),(c.averageCallLatencyMs/1000).toFixed(2)+'s']),['Independent GPT‑5.4 judge',d.judgeCost.calls,d.judgeCost.input,d.judgeCost.cached,d.judgeCost.output,amount(d.judgeCost.estimatedUSD),(d.judgeCost.averageCallLatencyMs/1000).toFixed(2)+'s']]);
body+='<p>Total known estimated cost: <b>'+amount(d.cost.reduce((n,c)=>n+c.estimatedUSD,0)+d.judgeCost.estimatedUSD)+'</b>. Per-phase usage, average cost per executed turn and missing-usage counts are in final-summary.json. Official rates per million: GPT‑4.1 mini input$0.40 / cached$0.10 / output$1.60; GPT‑5.4 input$2.50 / cached$0.25 / output$15.00. <a href="https://developers.openai.com/api/docs/models/gpt-4.1-mini">GPT‑4.1 mini documentation</a>; <a href="https://developers.openai.com/api/docs/models/gpt-5.4">GPT‑5.4 documentation</a>.</p>';
body+='<h2>Failure inventory by responsible layer</h2><p>All semantic/provider/expectation findings are below, including medium and naturalness issues. A failure can involve more than one layer; counts are not unique scenario counts. Model attribution is diagnostic and may remain UNKNOWN. Raw evidence and manual adjudication are retained.</p>';
for(const layer of [...new Set(failures.map(f=>f.layer))].sort()){const ff=failures.filter(f=>f.layer===layer);body+='<details><summary>'+esc(layer)+' — '+ff.length+' findings</summary>'+table(['Case','Severity','Finding','Evidence'],ff.map(f=>[f.id,f.severity,f.detail,f.evidence]))+'</details>';}
body+='<h2>Variance</h2><p>Every sample outcome is preserved.2/3 passing is UNSTABLE, never simply PASS.</p>'+table(['Model / suite / case','Passed','Failed','Other','Result'],variance.filter(v=>v.attempts>1).map(v=>[v.model+' / '+v.suite+' / '+v.id,v.pass+'/'+v.attempts,v.fail+'/'+v.attempts,v.other,v.result]));
body+='<h2>Release gates and limitations</h2><p><b>NO-GO.</b> Unsafe invoice intent, incorrect service/platform quotes, repeated questions and premature validation handoffs fail the release gates. Long-conversation behavior remains unvalidated. The evaluation did not deploy anything or authorize production rollout. V1 and rollback selection code remain byte-for-byte unchanged from preflight.</p><ul>'+summary.limitations.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul><p>No fixes were implemented. The incomplete paid evaluation can resume from pending-provider-work.json and saved provider-inconclusive keys after credits are restored; previous conclusive generations should not be repeated. Proposed next work, only after separate authorization: repair evidence-to-item state contracts and consent handling; investigate typed grounding/STRICT contracts against the actual catalogue; reconcile conflicting business data with the owner; then rerun frozen tests without weakening expectations.</p>';
put('evaluation-report.html',html('Joshspot V2 evaluation — NO-GO',body));
console.log(JSON.stringify({decision:summary.decision,counts:summary.scenarioCounts,reviewExamples:chosen.length,comparison,cost:d.cost.map(c=>({model:c.model,cost:c.estimatedUSD})),judgeCost:d.judgeCost.estimatedUSD,freezeUnchanged:true},null,2));
