const test=require('node:test'),assert=require('node:assert/strict');
const {resolve}=require('./resolver'),{validate}=require('./validation'),{decide}=require('./index');
const config={...require('../defaults').config,engineVersion:'v4',mode:'TEST',invoicesEnabled:true};
const records=()=>structuredClone(require('../../../evaluations/v3-golden-20261007/evaluation-snapshot.json').records);
const e={messageId:'now',text:'synthetic evidence'},messages=[{_id:'now',direction:'inbound',type:'text',text:e.text}];
function plan(type='ASK_PRICE',service='ACCOUNT_SETUP',platform='TIKTOK'){
 return {current_requests:[{id:'r1',type,service,platform,evidence:e}],facts:[],purchase_change:{operation:'REPLACE',items:[{service,platform,evidence:e}],evidence:e},readiness:{value:'INTERESTED',evidence:e},whole_purchase_cap:null,knowledge_needs:[],clarification:{needed:false,reason:'',missing_fields:[]}};
}
function ports(state={},status='NONE'){return {assertCurrent:async()=>{},persist:async s=>Object.assign(state,s),invoiceStatus:async()=>({status}),createInvoice:async()=>{throw Error('REAL_INVOICE_PORT_CALLED');},handoff:async()=>{throw Error('REAL_HANDOFF_PORT_CALLED');}};}
const run=(p,state={},ps=ports())=>resolve({plan:p,state,messages,records:records(),ports:ps,simulation:true,config});
function budget(p,amount=5000,duration=7,basis='DAILY_AD_SPEND'){p.facts=[{platform:p.current_requests[0].platform,service:p.current_requests[0].service,budget:{amount,basis,currency:'NGN'},duration_days:duration,package_duration_days:null,evidence:e}];return p;}
function output(message,questions=[]){return {message,unsupported_request_ids:[],covered_request_ids:['r1'],questions_asked:questions};}
test('setup price uses semantic catalogue mapping without campaign fields or model IDs',async()=>{const r=await run(plan());assert.equal(r.pack.quote.total,20000);assert.equal(r.pack.missing.length,0);assert.equal(r.next.purchaseItems[0].status,'confirmed');assert.ok(r.operations.includes('calculate_quote'));});
test('management daily budget uses unchanged calculator, approved testing default',async()=>{const r=await run(budget(plan('ASK_QUOTE','ADS_MANAGEMENT')));assert.equal(r.pack.quote.total,60000);assert.equal(r.pack.quote.lines[0].advertisingBudget,35000);assert.equal(r.pack.quote.items[0].creativeMode,'testing');});
test('recommendation resolves plans without inventing budget',async()=>{const r=await run(plan('ASK_RECOMMENDATION','ADS_MANAGEMENT'));assert.ok(r.pack.plans.length);assert.ok(!r.pack.missing.includes('budget'));});
test('15-day package retrieves265000=200000+65000',async()=>{const p=plan('ASK_BREAKDOWN','ADS_MANAGEMENT');p.facts=[{platform:'TIKTOK',service:'ADS_MANAGEMENT',budget:null,duration_days:null,package_duration_days:15,evidence:e}];const r=await run(p);assert.equal(r.pack.quote.total,265000);assert.equal(r.pack.quote.lines[0].advertisingBudget,200000);assert.equal(r.pack.quote.lines[0].managementFee,65000);});
test('mixed pairs and whole-purchase cap preserve scope',async()=>{const p=budget(plan('ASK_QUOTE','ADS_MANAGEMENT','META'),5000,10);p.purchase_change.items.push({platform:'TIKTOK',service:'ACCOUNT_SETUP',evidence:e});p.whole_purchase_cap={amount:100000,currency:'NGN',evidence:e};const r=await run(p);assert.ok(r.pack.quote.total<=100000);assert.deepEqual(r.pack.quote.items.map(i=>[i.platform,i.service]),[['meta','ads_management'],['tiktok','account_setup']]);assert.equal(r.pack.quote.lines.find(i=>i.platform==='tiktok').total,20000);});
test('course detour keeps management; explicit switch and return replace deliberately',async()=>{let r=await run(budget(plan('ASK_QUOTE','ADS_MANAGEMENT')));let p=plan('ASK_COURSE_DETAILS','COURSE');p.purchase_change={operation:'KEEP',items:[],evidence:null};r=await run(p,r.next);assert.equal(r.next.purchaseItems[0].service,'ADS_MANAGEMENT');assert.ok(r.pack.facts.some(f=>f.role==='course_price'&&f.value===8000));r=await run(plan('ASK_COURSE_DETAILS','COURSE'),r.next);assert.equal(r.next.purchaseItems[0].service,'COURSE');r=await run(budget(plan('ASK_QUOTE','ADS_MANAGEMENT')),r.next);assert.equal(r.pack.quote.total,60000);});
test('deferral suppresses invoice and payment question; fresh request resumes',async()=>{let r=await run(plan());const p=plan('ASK_PAYMENT_DETAILS');p.purchase_change={operation:'KEEP',items:[],evidence:null};p.readiness={value:'DEFERRED',evidence:e};r=await run(p,r.next);assert.equal(r.pack.actions.invoice,undefined);assert.ok(!r.pack.allowedQuestions.includes('payment'));p.readiness.value='READY_TO_PAY';r=await run(p,r.next);assert.equal(r.pack.actions.invoice.simulation,true);assert.equal(r.pack.actions.invoice.amount,20000);});
test('payment claim cannot mark paid',async()=>{const r=await run(plan('CLAIM_PAYMENT'),{},ports({},'pending'));assert.equal(r.pack.verifiedPayment,null);assert.ok(validate(output('Your payment is confirmed.'),r.pack).includes('FALSE_PAID_CLAIM'));});
test('human current evidence bypasses business data retrieval and simulates handoff',async()=>{const r=await run(plan('REQUEST_HUMAN'));assert.equal(r.pack.actions.handoff.accepted,true);assert.equal(r.next.ownership,'HUMAN');assert.deepEqual(r.operations,['handoff']);await assert.rejects(()=>run(plan('OTHER'),r.next),/HUMAN_OWNS/);});
test('multiple requests resolve independently; missing creative knowledge is explicit',async()=>{const p=plan('ASK_EXPECTED_RESULTS','ADS_MANAGEMENT');p.current_requests.push({...p.current_requests[0],id:'r2',type:'ASK_CREATIVE_REQUIREMENTS'});const r=await run(p);assert.ok(r.pack.knowledge.some(k=>k.topic==='ASK_EXPECTED_RESULTS'));assert.ok(r.pack.unresolvedRequests.some(q=>q.id==='r2'));});
test('knowledge eligibility honors metadata and excluded service',()=>{const {retrieve}=require('./knowledge');const rows=[{kind:'knowledge',key:'irrelevant',data:{v4Topics:['ASK_REQUIREMENTS'],v4Services:['ACCOUNT_SETUP'],preferredResponse:'setup only'}},{kind:'knowledge',key:'correct',data:{v4Topics:['ASK_REQUIREMENTS'],v4Services:['ADS_MANAGEMENT'],preferredResponse:'approved management'}}];assert.deepEqual(retrieve(rows,{topic:'ASK_REQUIREMENTS',platform:'META',service:'ADS_MANAGEMENT',query:''}).map(x=>x.source),['correct']);});

test('missing approved knowledge hands off before composition or invoice, preserving purchase',async()=>{
 const p=plan('ASK_TECHNICAL_HELP','ADS_MANAGEMENT');p.current_requests.push({...p.current_requests[0],id:'pay',type:'ASK_PAYMENT_DETAILS'});p.readiness={value:'READY_TO_PAY',evidence:e};budget(p);
 let calls=0;const state={};const api={pass:async stage=>{calls++;assert.equal(stage,'interpreter');return {value:p,metrics:{estimated_cost_usd:0}};}};
 const r=await decide({config,records:records().filter(x=>x.kind!=='knowledge'),messages,state,ports:ports(state),api});
 assert.equal(r.action,'handoff');assert.equal(r.handoff,'NO_APPROVED_KNOWLEDGE');assert.equal(calls,1);assert.equal(r.debug.answerPack.actions.invoice,undefined);assert.equal(state.purchaseItems[0].service,'ADS_MANAGEMENT');assert.equal(state.ownership,'HUMAN');assert.equal(r.response,config.fallbackResponse);
});

test('composer can reject insufficient retrieved facts; candidate is discarded, no repair',async()=>{
 const p=plan('ASK_SERVICE_INCLUSIONS','ACCOUNT_SETUP');let calls=0;const state={};const api={pass:async stage=>{calls++;return {value:stage==='interpreter'?p:{...output('An unsupported business claim'),unsupported_request_ids:['r1']},metrics:{estimated_cost_usd:0}};}};
 const r=await decide({config,records:records(),messages,state,ports:ports(state),api});
 assert.equal(r.handoff,'NO_APPROVED_KNOWLEDGE');assert.equal(calls,2);assert.equal(r.response,config.fallbackResponse);assert.equal(r.debug.composition[0].discarded,true);
});

test('authoritative price/payment facts do not require matching knowledge articles',async()=>{
 const p=plan('ASK_PRICE');p.knowledge_needs=[{topic:'ASK_PRICE',platform:'TIKTOK',service:'ACCOUNT_SETUP',query:'price'}];
 const r=await run(p);assert.equal(r.pack.actions.handoff,undefined);assert.deepEqual(r.next.unresolvedRequests,[]);
 const claim=await run(plan('CLAIM_PAYMENT'));assert.equal(claim.pack.actions.handoff,undefined);assert.equal(claim.pack.actions.payment.status,'NONE');
});

test('empty or other-platform knowledge cannot prevent a knowledge handoff',async()=>{
 const p=plan('ASK_EXPECTED_RESULTS','ADS_MANAGEMENT','META');const rows=records().filter(x=>x.kind!=='knowledge');rows.push({kind:'knowledge',key:'empty',data:{v4Topics:['ASK_EXPECTED_RESULTS'],facts:''}},{kind:'knowledge',key:'tiktok_only',data:{v4Topics:['ASK_EXPECTED_RESULTS'],v4Platforms:['TIKTOK'],facts:'Approved TikTok fact'}});
 const r=await resolve({plan:p,state:{},messages,records:rows,ports:ports(),simulation:true,config});assert.equal(r.pack.actions.handoff.reason,'NO_APPROVED_KNOWLEDGE');
});

test('missing customer duration stays a clarification, not a knowledge handoff',async()=>{
 const p=budget(plan('ASK_QUOTE','ADS_MANAGEMENT'));p.facts[0].duration_days=null;const r=await run(p);assert.equal(r.pack.actions.handoff,undefined);assert.ok(r.pack.missing.includes('duration'));
});

test('knowledge handoff rechecks ownership before assignment',async()=>{
 const p=plan('ASK_CREATIVE_REQUIREMENTS','ADS_MANAGEMENT');let checks=0;const ps=ports();ps.assertCurrent=async()=>{if(++checks>1)throw Error('V4_OWNERSHIP_CHANGED');};await assert.rejects(()=>run(p,{},ps),/OWNERSHIP_CHANGED/);
});
for(const text of ['The setup fee is 20k.','Setup costs 20,000 naira.','Setup fee: ₦20,000.','Setup fee is NGN 20,000.'])test(`natural trusted financial wording ${text}`,async()=>{const {pack}=await run(plan());assert.deepEqual(validate(output(text),pack),[]);});
test('same amount wrong role and invented amount rejected',async()=>{const {pack}=await run(budget(plan('ASK_QUOTE','ADS_MANAGEMENT')));assert.ok(validate(output('The setup fee is ₦25,000.'),pack).includes('UNSUPPORTED_MONEY_ROLE'));assert.ok(validate(output('The total is ₦90,000.'),pack).includes('UNSUPPORTED_MONEY_ROLE'));});

test('financial roles remain distinct in a natural combined sentence and word amounts',async()=>{const {pack}=await run(budget(plan('ASK_QUOTE','ADS_MANAGEMENT')));assert.deepEqual(validate(output('The advertising budget is ₦35,000 and the management fee is ₦25,000; the total is sixty thousand naira.'),pack),[]);assert.ok(validate(output('The total is ninety thousand naira.'),pack).includes('UNSUPPORTED_MONEY_ROLE'));});

test('negation in another clause cannot authorize a guarantee or false payment claim',async()=>{const {pack}=await run(plan());assert.ok(validate(output('No worries. Your payment is confirmed.'),pack).includes('FALSE_PAID_CLAIM'));assert.ok(validate(output('We cannot promise views, but you will definitely get customers.'),pack).includes('GUARANTEED_RESULTS'));assert.deepEqual(validate(output('We cannot guarantee sales.'),pack),[]);assert.ok(validate(output('Your invoice has been created.'),pack).includes('FALSE_INVOICE_CLAIM'));});

test('existing invoice does not force payment details into an unrelated answer',async()=>{const {pack}=await run(plan());pack.actions.payment={id:'trusted',accountNumber:'0123456789',url:'https://trusted.test/pay',paymentText:'Account number: 0123456789\nhttps://trusted.test/pay'};assert.deepEqual(validate(output('Setup fee is 20k.'),pack),[]);pack.requests[0].type='ASK_PAYMENT_DETAILS';assert.ok(validate(output('Setup fee is 20k.'),pack).includes('PAYMENT_DETAILS_MISMATCH'));assert.deepEqual(validate(output(pack.actions.payment.paymentText),pack),[]);});

test('Facebook and Instagram normalize to one Meta purchase; a switch clears old whole-purchase cap',async()=>{const p=plan('ASK_PRICE','ACCOUNT_SETUP','FACEBOOK');p.purchase_change.items.push({service:'ACCOUNT_SETUP',platform:'INSTAGRAM',evidence:e});const r=await run(p,{purchaseItems:[{platform:'TIKTOK',service:'ADS_MANAGEMENT'}],purchaseCap:100000});assert.equal(r.next.purchaseItems.length,1);assert.equal(r.pack.quote.total,30000);assert.equal(r.next.purchaseCap,null);});
test('ordinary customer budget and duration allowed; URL and envelope blocked',async()=>{const {pack}=await run(budget(plan('ASK_QUOTE','ADS_MANAGEMENT')));assert.deepEqual(validate(output('Your ad budget is 5k daily for 7 days. You can use two videos.'),pack),[]);assert.ok(validate(output('Pay https://bad.example/pay'),pack).includes('UNSUPPORTED_URL'));assert.ok(validate(output('{"messageId":"x"}'),pack).includes('INTERNAL_OUTPUT'));});
test('current evidence required; historical requests cannot be invented',async()=>{const p=plan();p.current_requests[0].evidence={messageId:'old',text:'old'};await assert.rejects(()=>run(p),/CURRENT_EVIDENCE/);});
test('composer repairs once only; no autonomous tool loop',async()=>{let calls=0;const state={},api={pass:async stage=>{calls++;return {value:stage==='interpreter'?plan():output('Setup fee is ₦15,000.'),metrics:{stage,total_tokens:1,estimated_cost_usd:0}};}};await assert.rejects(()=>decide({config,records:records(),messages,state,ports:ports(state),api}),/COMPOSITION_REJECTED/);assert.equal(calls,3);});
test('ownership invalidation blocks final send',async()=>{let stale=false;const p=ports();p.assertCurrent=async()=>{if(stale)throw Error('V4_OWNERSHIP_CHANGED');};const api={pass:async stage=>{if(stage==='composer')stale=true;return {value:stage==='interpreter'?plan():output('Setup fee is 20k.'),metrics:{estimated_cost_usd:0}};}};await assert.rejects(()=>decide({config,records:records(),messages,ports:p,api}),/OWNERSHIP_CHANGED/);});
test('test session ignores client state and never invokes financial port',async()=>{const api={pass:async stage=>({value:stage==='interpreter'?{...plan('ASK_PAYMENT_DETAILS'),readiness:{value:'READY_TO_PAY',evidence:e}}:output('Your test invoice is prepared.'),metrics:{estimated_cost_usd:0}})};const state={};const r=await decide({config,records:records(),messages,state,ports:ports(state),api,simulation:true});assert.equal(r.wouldGenerateInvoice,true);});
test('all engines selectable, default remains V1, V4 live manual gate',()=>{const {version}=require('../runtime');for(const engineVersion of ['v1','v2','v3','v4'])assert.equal(version({engineVersion,mode:'DRAFT'},{}),engineVersion);assert.equal(version({},{}),'v1');assert.throws(()=>version({engineVersion:'v4',mode:'LIVE'},{}),/approval/);assert.equal(require('../config').validateConfig({...config,mode:'TEST'}).engineVersion,'v4');});
test('model adapter sends structured outputs, no tools, separate stage models',async()=>{const before=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='fake-for-offline-test';const bodies=[];try{const api=require('./model').client({config,transport:async req=>{bodies.push(req.data);return {data:{status:'completed',usage:{input_tokens:10,output_tokens:2,total_tokens:12},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(req.data.model===config.v4InterpreterModel?plan():output('Okay.'))}]}]}};}});await api.pass('interpreter',{});await api.pass('composer',{});assert.equal(bodies[0].model,'gpt-6.1-sol');assert.equal(bodies[1].model,'gpt-6-luna');assert.ok(bodies.every(b=>!b.tools&&b.store===false&&b.text.format.strict));}finally{if(before===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=before;}});
test('composer receives delivered history and current interruption, not failed drafts',async()=>{
 const p=plan('ASK_PRICE');const state={};let seen;
 const api={pass:async(stage,input)=>{if(stage==='interpreter')return {value:p,metrics:{}};seen=input;return {value:output('Would you like to proceed?',[{field:'proceed',purpose:'purchase'}]),metrics:{}};}};
 await decide({config,records:records(),messages,state,ports:ports(state),api,history:[{direction:'outbound',status:'sent',text:'Which platform?'},{direction:'inbound',text:'TikTok'},{direction:'outbound',status:'failed',text:'What is your budget?'}]});
 assert.equal(seen.conversation.history.length,2);assert.equal(seen.conversation.current[0].text,e.text);assert.ok(!seen.allowedQuestions.includes('platform'));
});
